<h1><?php echo Mage::helper('bitbull_bancasellapro')->__('Attendi un attimo') ?></h1>
<div>
    <p><?php echo Mage::helper('bitbull_bancasellapro')->__('A breve sarai reindirizzato') ?></p>
</div>
<script type="text/javascript">
    //<![CDATA[

    var pares = '<?php echo $this->getPARes() ?>',
        cartUrl = '<?php echo $this->getCartUrl() ?>',
        bs = parent.BancaSellaForm;

    if (typeof bs == 'undefined') {
        parent.location.href = cartUrl;
    } else {
        bs.sendPares(pares);
    }
    //]]>
</script>
