
<?php
?>
<div id="gritter-notice-wrapper" style="display:none">
	<div class="gritter-item-wrapper" id="gritter-item-3">
		<div class="gritter-top"></div>
		<div class="gritter-item">
			<div class="gritter-close"></div>
			<img id="gritter-pro-image" class="gritter-image" src="http://cdn.valuebasket.com/808AA1/vb//images/product/13814-AA-NA_m.jpg">
			<div class="gritter-with-image">
				<span id="gritter-title" class="gritter-title">Article ajouté au panier</span>
				<p id="pro_title">Film Protecteur Capdase ScreenGUARD pour Samsung Galaxy S4 Mini</p>
			</div>
			<div style="clear:both"></div>
		</div>
		<div class="gritter-bottom"></div>
	</div>
</div>

