<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<?php
    /**
    * Product list template
    *
    * @see Mage_Catalog_Block_Product_List
    */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>


<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>


        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>

            <?php
                $isRivista = false;
                $attributeSetModel = Mage::getModel("eav/entity_attribute_set");
                $attributeSetModel->load($_product->getAttributeSetId());
                if($attributeSetModel->getAttributeSetName() == "Riviste")
                {
                    $isRivista = true;
                }
            ?>

            <?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
                    <?php endif;  ?>
                        <?php if(!$isRivista): ?>
                            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php
                                        $sb=0;
                                        $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                                        if(count($imagesCount) >1 ):
                                            $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                            if($_images)
                                            {
                                                $sb=1;
                                            ?>
                                            <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize(400,537); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                            <?php }
                                            endif;?>
                                    <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400,537); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                    <!--<img src="<?php echo $this->getSkinUrl('images/')?>home_main_callout.jpg" class="sbmoreview"/>-->
                                </a>
                                <div class="datiProd">
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    <?php if($_product->getTypeId() != "bundle"): ?>
                                        <p class="sku"><?php echo $_product->getSku(); ?></p>
                                        <div class="doubleData">
                                            <span class="tg">Tg. <?php echo $_product->getAttributeText("size"); ?></span>
                                            <span class="lvl">Livello: <?php echo $_product->getAttributeText("livello"); ?></span>
                                        </div>
                                        <?php if($_product->getProdottoNuovo()): ?>
                                            <span class="new">NUOVO</span>
                                        <?php endif; ?>
                                        <?php if($_product->getSpecialPrice()): ?>
                                            <span class="new promo">PROMO</span>
                                        <?php endif; ?>
                                         <?php if($_product->getPagamento() == 28): ?>
                                            <span class="new free"><?php echo $_product->getAttributeText("pagamento"); ?></span>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <p class="sku"><?php echo $_product->getShortDescription(); ?></p>
                                        <div class="doubleData">
                                            <span class="lvl">Livello: <?php echo $_product->getAttributeText("livello"); ?></span>
                                        </div>
                                    <?php endif; ?>

                                    <?php if($_product->getPrezzoVisibile() == 1): ?>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php endif; ?>

                                    <div class="actions">
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                            <?php endif; ?>
                                        </ul>
                                        <?php if($_product->isSaleable()): ?>
                                            <?php if($_product->getTypeId() != "downloadable"): ?>
                                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                                </button>
                                            <?php else: ?>

                                                <button type="button" title="<?php echo $this->__('Download') ?>" class="button btn-down" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    <span><span><?php echo $this->__('Download') ?></span></span>
                                                </button>

                                            <?php endif; ?>
                                        <?php else: ?>
                                            <!-- prodotto esaurito -->
                                            <button type="button" title="<?php echo $this->__('Scopri') ?>" class="button btn-scopri-down" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                                <span><span><?php echo $this->__('Scopri') ?></span></span>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                    <?php if($_product->getTypeId() == "configurable"): ?>
                                        <div class="addConf">
                                            <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>" method="post" id="add-cart-form-<?php echo $_product->getId(); ?>">
                                                <input type="hidden" name="related_product" value="" />
                                                <input type="hidden" name="qty" value="1" />
                                                <input type="hidden" name="cpid" value="" />
                                                <input type="hidden" name="super_attribute[149]" value="" />
                                                <?php
                                                $conf = new Mage_Catalog_Block_Product_View_Type_Configurable();
                                                $list = $conf->setData("product", $_product)->getAllowProducts();
                                                foreach($list as $p): ?>
                                                  <button class="button select-product t-<?= $p->getTipologia(); ?>" data-sid="<?= $p->getId(); ?>" data-tipologia="<?= $p->getTipologia(); ?>" data-cid="<?= $_product->getId(); ?>">
                                                     <span><?= $p->getAttributeText('tipologia')." ". $this->helper("core")->formatPrice($p->getFinalPrice()); ?></span>
                                                  </button>
                                                <?php endforeach; ?>
                                            </form>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </li>
                        <?php else: ?>
                            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <?php
                                    $sb=0;
                                    $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                                    if(count($imagesCount) >1 ):
                                        $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                        if($_images)
                                        {
                                            $sb=1;
                                            ?>
                                            <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize(203,270); ?>" width="203" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                        <?php }
                                    endif;?>
                                    <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(203,270); ?>" width="203" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </a>
                                <div class="datiProd">
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    <p class="sku"><?php echo $_helper->productAttribute($_product, $_product->getSottoTitolo(), 'sotto_titolo') ?></p>

                                    <?php
                                    $checkDate = Mage::app()->getLocale()->isStoreDateInInterval(Mage::app()->getStore(), $_product->getNewsFromDate(),$_product->getNewsToDate());
                                    ?>
                                    <?php if($_product->getEdicola() == 1 && !is_empty_date($_product->getNewsFromDate())&& $checkDate): ?>
                                        <span class="new free edicola">In Edicola</span>
                                    <?php endif; ?>

                                </div>
                                <div><?php echo substr(strip_tags($_product->getShortDescription()), 0, 55); ?>...</div>
                                <button type="button" title="Scopri di pi&ugrave;" class="button btn-scopri" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                    <span><span>Scopri</span></span>
                                </button>
                            </li>
                        <?php endif ?>

            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>
    <script type="text/javascript">
        decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);
    </script>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>