<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<?php
    $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
    if($config == 1):
        $i == 1;
    ?>
    <?php if($this->getItems()->getSize()): ?>
        <div class="block block-related">
            <div class="block-content">
                <ol class="mini-products-list products-grid" id="block-related">
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php if($i == 3)  break; ?>
                        <li class="item <?php if($i==2):?>last<?php endif; ?>">
                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
                                <?php
                                    $sb=0;
                                    $imagesCount = Mage::getModel('catalog/product')->load($_item->getId())->getMediaGalleryImages();
                                    if(count($imagesCount) >1 ):
                                        $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                        if($_images)
                                        {
                                            $sb=1;
                                        ?>
                                        <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail', $_images->getFile())->resize(400,537); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                        <?php }
                                        endif;?>

                                <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(400,537) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                            <div class="datiProd">
                                <h2 class="product-name">
                                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                                </h2>
                                <?php if($_item->getTypeId() != "bundle"): ?>
                                    <p class="sku"><?php echo $_item->getSku(); ?></p>
                                    <div class="doubleData">
                                        <span class="tg">Tg. <?php echo $_item->getAttributeText("size"); ?></span>
                                        <span class="lvl">Livello: <?php echo $_item->getAttributeText("livello"); ?></span>
                                    </div>
                                    <?php if($_item->getProdottoNuovo()): ?>
                                        <span class="new">NUOVO</span>
                                    <?php endif; ?>

<!--                                <?php if($_item->getPagamento() == 28): ?>
                                        <span><?php echo $_item->getAttributeText("pagamento"); ?></span>
                                    <?php endif; ?> -->

                                <?php else: ?>
                                    <p class="sku"><?php echo $_item->getShortDescription(); ?></p>
                                    <div class="doubleData">
                                        <span class="lvl">Livello: <?php echo $_item->getAttributeText("livello"); ?></span>
                                    </div>
                                <?php endif; ?>

                                <?php if($_item->getPrezzoVisibile() == 1): ?>
                                    <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                                <?php endif; ?>

                                <div class="actions">
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?= $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?>
                                            </a></li>
                                        <?php endif; ?>
                                    </ul>
                                    <?php if($_item->isSaleable()): ?>
                                         <?php if($_item->getTypeId() != "downloadable"): ?>
                                            <button type="button" title="<?= $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?= $this->getAddToCartUrl($_item) ?>')">
                                                <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                            </button>
                                        <?php else: ?>
                                            <button type="button" title="<?= $this->__('Download') ?>" class="button btn-down" onclick="setLocation('<?= Mage::helper("checkout/cart")->getAddUrl($_item); ?>');">
                                                <span><span><?php echo $this->__('Download') ?></span></span>
                                            </button>

                                        <?php endif; ?>
                                    <?php else: ?>
                                        <!-- prodotto esaurito -->
                                        <button type="button" title="<?php echo $this->__('Scopri') ?>" class="button btn-scopri-down" onclick="setLocation('<?php echo $_item->getProductUrl() ?>')">
                                            <span><span><?php echo $this->__('Scopri') ?></span></span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                                
                               
                                <?php if($_item->getTypeId() == "configurable"): ?>
                                    <div class="addConf">
                                        <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($_item); ?>" method="post" id="add-cart-form-<?php echo $_item->getId(); ?>">
                                            <input type="hidden" name="related_product" value="" />
                                            <input type="hidden" name="qty" value="1" />
                                            <input type="hidden" name="cpid" value="" />
                                            <input type="hidden" name="super_attribute[149]" value="" />
                                            <?php
                                            $conf = new Mage_Catalog_Block_Product_View_Type_Configurable();
                                            $list = $conf->setData("product", $_item)->getAllowProducts();
                                            foreach($list as $p): ?>
                                                <button class="button select-product t-<?= $p->getTipologia(); ?>" data-sid="<?= $p->getId(); ?>" data-tipologia="<?= $p->getTipologia(); ?>" data-cid="<?= $_product->getId(); ?>">
                                                    <span><?= $p->getAttributeText('tipologia')." ". $this->helper("core")->formatPrice($p->getFinalPrice()); ?></span>
                                                </button>
                                            <?php endforeach; ?>
                                        </form>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </li>
                        <?php $i++; ?>
                        <?php endforeach ?>
                </ol>
                <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
            </div>
            <script type="text/javascript">
                //<![CDATA[
                $$('.related-checkbox').each(function(elem){
                    Event.observe(elem, 'click', addRelatedToProduct)
                });

                var relatedProductsCheckFlag = false;
                function selectAllRelated(txt){
                    if (relatedProductsCheckFlag == false) {
                        $$('.related-checkbox').each(function(elem){
                            elem.checked = true;
                        });
                        relatedProductsCheckFlag = true;
                        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
                    } else {
                        $$('.related-checkbox').each(function(elem){
                            elem.checked = false;
                        });
                        relatedProductsCheckFlag = false;
                        txt.innerHTML="<?php echo $this->__('select all') ?>";
                    }
                    addRelatedToProduct();
                }

                function addRelatedToProduct(){
                    var checkboxes = $$('.related-checkbox');
                    var values = [];
                    for(var i=0;i<checkboxes.length;i++){
                        if(checkboxes[i].checked) values.push(checkboxes[i].value);
                    }
                    if($('related-products-field')){
                        $('related-products-field').value = values.join(',');
                    }
                }
                //]]>
            </script>
        </div>
        <?php endif ?>
    <?php endif ?>
<script type="text/javascript">
    jQuery(document).on("click", "button.select-product", function(e)
    {
        e.preventDefault();
        $form = jQuery("#add-cart-form-" + jQuery(this).data("cid"));
        jQuery(" > input[name=product]", $form).val(jQuery(this).data("sid"));
        jQuery(" > input[name=cpid]", $form).val(jQuery(this).data("cid"));
        jQuery(" > input[name='super_attribute[149]']", $form).val(jQuery(this).data("tipologia"));
        $action = $form.attr("action");
        $action = $action.replace("/product/" + jQuery(this).data("cid"), "/product/" + jQuery(this).data("sid"));
        $form.attr("action", $action);
        $form.submit();
    });
</script>
