<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>
        <p class="block-subtitle"><?php echo Mage::helper('catalog')->__('Stai filtrando per') ?></p> 
    <?php foreach ($_filters as $_filter): ?>
            <?php echo $_filter->getLabel() ?>
    <?php endforeach; ?>
    <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 7)): ?>
    <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>"><?php echo Mage::helper('catalog')->__('Clear All') ?></a></div>
    <?php endif; ?>
<?php endif; ?>