<?php
/**
 * @copyright   Copyright (c) 2009-2014 Amasty (http://www.amasty.com)
 */ 
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_requests = $this->getRequests(); ?>
<div class="page-title title-buttons">
    <h1>I miei resi</h1>
</div>

<?php $_orders = $this->getAvailableOrders(); ?>
<?php if($_orders) { ?>
    <div class="seleziona">
        <select id="orders">
            <?php
                foreach ($_orders as $orderId => $incrementId){
                    ?><option url="<?php echo $this->getNewUrl($orderId) ?>"><?php echo $incrementId;?></option><?php
                }
            ?>
        </select>
        <div class="clear"></div>
        <button type="button" class="button btn-blue" style="margin:20px 0;" onclick="window.location=$(orders).options[$(orders).selectedIndex].getAttribute('url')">
            <span><span>Richiedi</span></span>
        </button>
    </div>
<?php } ?>


<div class="dashboard">
    <div class="box-account box-recent">
        <?php echo $this->getPagerHtml(); ?>
        <?php if($_requests->getSize()): ?>
        <table class="data-table" id="my-orders-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Data</th>
                    <th>Ordine #</th>
                    <th>Stato</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_requests as $_request): ?>
                <tr>
                    <td><?php echo $_request->getId() ?></td>
                    <td><span class="nobr"><?php echo $this->formatDate($_request->getCreated()) ?></span></td>
                    <td><?php echo $_request->getIncrementId() ?></td>
                    <td><em><?php echo $_request->getStatusLabel() ?></em></td>
                    <td class="a-center">
                        <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_request) ?>"><?php echo $this->__('View') ?></a> |
                        <a onclick="if (!confirm('<?php print $this->__("Delete")?>?')) return false;" href="<?php echo $this->getDeleteUrl($_request) ?>"><?php echo $this->__('Delete') ?></a>
                        </span>
                    </td>

                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php else: ?>
            <p class="buttons-set">Non hai effettuato nessuna richiesta di reso</p>
        <?php endif ?>
        <script type="text/javascript">decorateTable('my-orders-table');</script>
        <?php echo $this->getPagerHtml(); ?>
    </div>
</div>





