4<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<?php
 $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
    if($config == 1):
    ?>
    <?php if(count($this->getItemCollection()->getItems())): ?>
        <div class="box-collateral box-up-sell">
            <ol class="mini-products-list products-grid" id="block-upsell">
                <?php $this->resetItemsIterator() ?>
                <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                            <li class="item <?php if($_j==2):?>last<?php endif; ?>">
                                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                                    <img class="img-preview" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(400,537) ?>"  alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                                </a>

                                <div class="datiProd">
                                    <h2 class="product-name">
                                        <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
                                            <?php echo $this->htmlEscape($_link->getName()) ?>
                                        </a>
                                        <p class="sku"><?php echo $_link->getShortDescription(); ?></p>
                                    </h2>

                                </div>

                            </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    <?php endfor; ?>
            </ol>
            <script type="text/javascript">decorateTable('upsell-product-table')</script>
        </div>
        <?php endif ?>
    <?php endif ?>
