<?php
/**
 * Star Plugins Cloud Zoom - Magento Extension
 * @package     StarPlugins_CloudZoom
 * @category    StarPlugins
 * @copyright   Copyright 2013 Star Plugins. (http://www.starplugins.com)
 * @version:    1.0
 */

$product      = $this->getProduct();
$helper       = Mage::helper('starplugins_cloudzoom');
$outputHelper = $this->helper('catalog/output');

    $isRivista = false;
    $isCreazioni = false;
    // Get attribute set model.
    $model = Mage::getModel('eav/entity_attribute_set');

    // Get attribute set id.
    $attributeSetId = $product->getAttributeSetId();
    $attributeSet = $model->load($attributeSetId);

    // This is attribute set name.
    $attributeSetName = $attributeSet->getAttributeSetName();
   /* print_r($attributeSetName);*/

    if($attributeSet->getAttributeSetName() == "Riviste")
    {
        $isRivista = true;
    }
    if($attributeSet->getAttributeSetName() == "Creazioni utenti")
    {
        $isCreazioni = true;
    }

if ($product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_BUNDLE && !$isRivista):


    function under2camel($str) {
        $regexp = '#_(.)#e';
        return preg_replace($regexp, "strtoupper('\\1')", $str);
    }

    $configVariables = array(
        "tint_color",
        "tint_opacity",
        "animation_time",
        "zoom_position",
        "zoom_offset_x",
        "zoom_offset_y",
        "zoom_fly_out",
        "zoom_size_mode",
        "caption_position",
        "variable_magnification",
        "start_magnification",
        "min_magnification",
        "max_magnification",
        "easing",
        "auto_inside"

    );

// Convert config to a JS object.
    $jsData = "{";
    foreach($configVariables as $var) {
        $value = $helper->getConfigData($var);
        if(!is_numeric($value)) $value = "\"".$value."\"";
        $jsData.= under2camel($var).": $value, ";
    }
    $jsData = rtrim($jsData, ', ')."}";
    ?>

    <?php
    // Include Fancy Box files if required.
    if ($helper->getConfigData("use_fancybox")) {
        echo '<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox.css"/>';
        echo '<script type="text/javascript" src="/fancybox/jquery.fancybox.pack.js"></script>';
    }
    ?>


    <script type="text/javascript">
        //<![CDATA[
        // Setup Fancy Box click detection if required.
        jQuery(function(){
            if (jQuery.fancybox != undefined) {
                jQuery('.cloudzoom').bind('click',function(){
                    var cloudZoom = jQuery(this).data('CloudZoom');   // On click, get the Cloud Zoom object,
                    cloudZoom.closeZoom();                       // Close the zoom window (from 2.1 rev 1211291557)
                    jQuery.fancybox.open(cloudZoom.getGalleryList()); // and pass Cloud Zoom's image list to Fancy Box.
                    return false;
                });
            }
        });
        jQuery.extend(jQuery.fn.CloudZoom.defaults,<?php echo $jsData;?>);
        CloudZoom.quickStart();

        //]]>
    </script>

    <?php
    if (!$isCreazioni){
        $bigImageWidth = $helper->getConfigData("big_image_width");
        $bigImageHeight = $helper->getConfigData("big_image_height");
        $smallImageWidth = $helper->getConfigData("small_image_width");
        $smallImageHeight = $helper->getConfigData("small_image_height");
        $zoomWidth = $helper->getConfigData("zoom_width");
        $zoomHeight = $helper->getConfigData("zoom_height");
    } else {
        $bigImageWidth = $helper->getConfigData("big_image_width");
        $bigImageHeight = $helper->getConfigData("big_image_height");
        $smallImageWidth = 415;
        $smallImageHeight = 555;
        $zoomWidth = $helper->getConfigData("zoom_width");
        $zoomHeight = $helper->getConfigData("zoom_height");
    }
    echo "<style type='text/css'>.cloudzoom-zoom {width:{$zoomWidth}px; height: {$zoomHeight}px;}</style>";

    if ($product->getImage() != 'no_selection' && $product->getImage()): ?>
        <p class="product-image">
            <?php $zPath = $this->helper('catalog/image')->init($product, 'image')->resize($bigImageWidth, $bigImageHeight);?>
            <a href="<?php echo $zPath; ?>" id='zoom1' >
                <img class="cloudzoom" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($smallImageWidth, $smallImageHeight);?>"
                     alt='' data-cloudzoom =""
                     title="<?php echo $this->htmlEscape($this->getImageLabel());?>" />
            </a>
        </p>
    <?php else: ?>
        <p class="product-image">
            <?php
            $_img = '<img class="cloudzoom" src="'.$this->helper('catalog/image')->init($product, 'image')->resize($smallImageWidth).'"
            alt="'.$this->htmlEscape($this->getImageLabel()).'" 
                title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="more-views">
        <ul>
            <?php // Additional thumb copy of main image ?>
            <!--<?php $zPath = $this->helper('catalog/image')->init($product, 'image')->resize($bigImageWidth, $bigImageHeight);?>
         <li>
            <a href='<?php echo $zPath; ?>' title='<?php echo $this->htmlEscape($this->getImageLabel()) ?>' >
            <img class='cloudzoom-gallery'
                data-cloudzoom="useZoom: '.cloudzoom', image: '<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($smallImageWidth, $smallImageHeight);?>' "
                src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($smallImageWidth, $smallImageHeight);?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"
                title='<?php echo $this->htmlEscape($this->getImageLabel()) ?>'
                />
            </a>
        </li>-->
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php $zoomPath = $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>
                <li class="thumbnail-wrapper"<?php echo $_image->getFile() == $product->getImage() ? ' style="display:none;"' : '' ?>>
                    <a href='<?php echo $zoomPath; ?>' title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'>
                        <img class='cloudzoom-gallery'
                             data-cloudzoom="useZoom: '.cloudzoom', image: '<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($smallImageWidth, $smallImageHeight);?>' "
                             src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(100, 133);?>"
                             alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"
                             title="<?php echo $this->htmlEscape($_image->getImageLabel()) ?>"
                            />
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery("li.thumbnail-wrapper > a").on("mouseup", function(){
                jQuery("li.thumbnail-wrapper").show();
                jQuery(this).parent("li").hide();
            })
        })
    </script>
<?php endif; ?>


<?php else: ?>

    <?php if($isRivista): ?>
        <p class="product-image">
            <img src="<?= $this->helper('catalog/image')->init($product, 'image')->resize(482, 616)->keepFrame(false); ?>"
                 title="<?php echo $this->htmlEscape($this->getImageLabel());?>" />
        </p>

    <?php else: ?>
        <p class="product-image bbbb">
            <img src="<?= $this->helper('catalog/image')->init($product, 'image')->resize(482, 642)->keepFrame(false); ?>"
                 title="<?php echo $this->htmlEscape($this->getImageLabel());?>" />
        </p>
    <?php endif; ?>

<?php endif; ?>


<?php if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE): ?>
    <div class="dati-prod">
        <!--<ol>
                <li><a href="https://www.facebook.com/sharer.php?u=<?php /*echo $urlPage; */?>" class="fb"></a></li>
                <li><a href="http://twitter.com/intent/tweet?url=<?php /*echo $urlPage; */?>" class="tw"></a></li>
                <li><a href="https://plus.google.com/share?url=<?php /*echo $urlPage; */?>" class="go"></a></li>
                <li><a href="https://pinterest.com/pin/create/button/?url=<?php /*echo $urlPage; */?>&media=<?/*= $this->helper('catalog/image')->init($product, 'image'); */?>" class="pi"></a></li>
            </ol>-->
    </div>
<?php endif; ?>
