<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
?>
<div class="opc-wrapper-opc">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Checkout')?></h1>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('frase-checkout')->toHtml();?>
    </div>

    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
        <?php echo $this->getChildHtml('login');?>
    <?php endif;?>
    <div class="clear"></div>

    <div class="opc-col-left">
        <form id="opc-address-form-billing" method="post">
            <?php echo $this->getChildHtml('billing')?>
        </form>

        <form id="opc-address-form-shipping" class="hidden" method="post">
            <?php echo $this->getChildHtml('shipping')?>
        </form>

    </div>

    <div class="opc-col-center">
        <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
            <div class="shipping-block">
                <h3><?php echo $this->__('Shipping Method')?></h3>
                <div id="shipping-block-methods">
                    <?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
                </div>
            </div>
        <?php endif;?>
        <div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin virtualposition<?php endif;?>">
            <h3><?php echo $this->__('Payment Method')?></h3>
            <?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
        </div>

        <div class="discount-block">
            <h3><?php echo $this->__('Hai un codice sconto?')?></h3>
            <?php echo $this->getChildhtml('coupon');?>
        </div>


    </div>

    <div class="opc-col-right <?php if ($this->getOnepage()->getQuote()->isVirtual()):?> virtualpositionriep<?php endif;?>">
        <h3>Repilogo del tuo ordine</h3>
        <div id="opc-review-block">
            <?php echo $this->_getReviewHtml()?>
        </div>
    </div>
</div>
<script>
    IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
    <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
    IWD.OPC.Checkout.isVirtual = true;
    <?php endif;?>
</script>

<div class="opc-ajax-loader">
    <div id="floatingCirclesG">
        <div class="f_circleG" id="frotateG_01"></div>
        <div class="f_circleG" id="frotateG_02"></div>
        <div class="f_circleG" id="frotateG_03"></div>
        <div class="f_circleG" id="frotateG_04"></div>
        <div class="f_circleG" id="frotateG_05"></div>
        <div class="f_circleG" id="frotateG_06"></div>
        <div class="f_circleG" id="frotateG_07"></div>
        <div class="f_circleG" id="frotateG_08"></div>
    </div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">

    <div class="opc-messages">
        <a class="close-message-wrapper"></a>
        <div class="opc-message-container"></div>
        <div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('CHIUDI')?></span></span></button></div>
    </div>
</div>