<div class="megaforum">
<h1>Mega Forum</h1>


<?php 
$forum = Mage::getModel('megaforum/forum')->getCollection(); 
$fcount = $forum->count();
 
$id = $this->getRequest()->getParam("id");
$topic = Mage::getModel('megaforum/topic')->load($id); 
$viewcount = $topic->getViews();
$topic->setViews($viewcount+1)->save();

$watchlist = Mage::getModel('megaforum/watchlist')->getCollection()->count(); 
?>

<table><tr>
	    <td>	
	        <a class="rss-value" href="<?php echo Mage::getUrl('megaforum/index/mywatchlist'); ?>"> <strong><?php echo "[".$watchlist."]" ?></strong></a>&nbsp;
		<a href="<?php echo Mage::getUrl('megaforum/index/watchlist')."id/".$topic->getTopicId();  ?>"><img src="<?php echo $this->getSkinUrl('images/bookmark-btn.png') ?>" /></a>							
	    </td></tr>
				
</table>
<br/>
<div id="button"  class="forum-buttons">
<table><tr>

		<td>
			<a href="<?php echo Mage::getUrl('megaforum/forum/rss'); ?>"><img src="<?php echo $this->getSkinUrl('images/rss-btn.png') ?>" /></a>&nbsp;
	       </td>
		<td style="float:right;">	
			<a href="<?php echo Mage::getUrl('megaforum/index/mypost')."id/".$topic->getTopicId(); ?>"><button class="forum-button"><strong>Add New post</strong></button></a>							
		</td>
</tr></table><br>
</div>
<br/>
<br/>
<form method="post" action="<?php echo Mage::getUrl('megaforum/index/search'); ?>">
<table>
	<tbody><tr>
		<td width="445">
			<div style="width:300px; height:30px;" >
				<table>
					<tr>
										<td class="list">
											Go To : &nbsp;
										</td>
										<td>
											<select class="selection" onchange="slectBox(this)" id='selectedForum'>  
													  <option value="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => 0));  ?>">Index</option>			
													  <?php foreach($forum as $forums){ ?>
													  <option id="<?php echo $forums->getForumId(); ?>" value="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forums->getForumId()));  ?>"
													  <?php if($id == $forums->getForumId()) echo "selected"; ?>> <?php echo $forums->getForumName(); ?> </option>					 
													  <?php
													  }
													  ?>
											</select>
										</td>
									</tr>
							</table><br>
					</div>
			</td>
						
			<td>
			<div class="space-search">
				<input type="text" name="query" value="SEARCH" onblur="if(this.value == '') { this.value='SEARCH'}" onfocus="if (this.value == 'SEARCH') {this.value=''}">      
				<button class="image-button" title="Search" type="submit"><span>Search Forum</span></button>	</div>		
			</td>
				</tr>
	</tbody></table>
</form>

<dl class="order-info"><dt><ul id="order-info-tabs"><li class="current first last">
     Topic Description :</li>
</dt><dd>
  <?php echo $topic->getMessage(); ?>
</ul>
<script type="text/javascript">
  decorateGeneric($('order-info-tabs').select('LI'),['first','last']);
</script></dd></dl>

<div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $post = $this->getCollection(); ?>
<?php echo $this->getToolbarHtml(); ?>

<table class="forum">

	<thead> 
		<tr>
			
			<th class="post1">Post Information</th>
			<th>Post</th>
		</tr>
	</thead>
	
	<tbody>
	<?php $_iterator = 0; ?>
	
	<?php
	foreach($post as $posts){
	$customerName = Mage::getModel('customer/customer')->load($posts->getPostedBy());
	$activePosts = Mage::getModel('megaforum/post')->load($posts->getStatus()); 
	?>
	
	<?php if($posts['status'] == "Active") { ?>
	<tr class="<?php if( ++$_iterator == sizeof($fcount) ): ?><?php endif; ?>  <?php echo ($_iterator % 2 == 0) ? 'even' : 'odd'; ?>">
				
	<?php $forumUser = Mage::getModel('megaforum/forumuser')->getCollection()->addFieldToFilter("user_id",$customerName->getId())->getFirstItem(); ?>	
	<td><img src="<?php echo Mage::getBaseUrl('media').$forumUser->getImage();?>" alt="" width="50" height="50" title="" style="float:left; margin-right:10px; 	border:2px solid #777575;" />
	<div ><img src="<?php echo $this->getSkinUrl('images/private-icon.png') ?>" /> &nbsp;
	<a href="<?php echo Mage::getUrl('megaforum/index/privatemsg')."id/".$posts->getPostId() ?>">Send Private Message</a><br>
	Posted By : <?php echo $customerName->getFirstname(); ?><br>Posted At : <?php echo $posts->getPostedAt(); ?></div></td>


	<td><p><?php echo $posts->getPostText(); ?></p><br/>
	<ul class="links a-right">
	<li><strong><a href="<?php echo Mage::getUrl('megaforum/index/edit')."id/".$posts->getPostId() ?>">Edit</a><span class="separator"> |</span></li>
	<li><a href="<?php echo Mage::getUrl('megaforum/index/delete')."id/".$posts->getPostId() ?>">Delete</a></strong></li>
	</ul>
	</td>
	
	</tr>	
	<?php
	}
	}
	?>
	</tbody>
</table>

</div>
</div>

<script language='javascript'>

function slectBox(sel) {
var value = sel.options[sel.selectedIndex].value; 
self.location=value;
}

</script>

