<div style="padding:10px; background:#f9f9f9; border:1px #f1f1f1 solid; overflow:auto; ">
 <div style="background:#fff; padding:6px; overflow:auto;">
<!-- seller profile img -->
<div class="seller-review-image"><img width="80" src="http://www.exagle.in/skin/frontend/default/exaglein/images/empty-thamb-image.gif"></div>
<!-- seller profile  img end-->
 <!-- seller profile -->
 <div class="seller-profile-col2">
 <h2 style="color:#1162B7;">stylelok</h2>
 <p><span>Seller From :</span><span>2013-04-28 11:33:54</span></p>
 <ul>
 <li><a href="http://www.exagle.in/profile/index/new/?username=stylelok">Send a message to seller</a></li>
 <li><a href="http://www.exagle.in/profile/product/list/?store=stylelok">View All product from this seller</a></li>
 </ul>
<!--<iframe scrolling="no" frameborder="0" allowtransparency="true" style="border:none; overflow:hidden; width:100%; height:80px;" src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.exagle.in/profile/index/sellerreview/?id=19204&amp;layout=button_count&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80"></iframe>-->
 </div>
  <!-- seller profile end -->
 <!-- certified seller -->
 <div class="seller-profile-col3">
 <!--<div>Positive Feedback ( <span style="color:#1162B7;">last 12 months</span> ): <span style="color:#1162B7;">100%</span></div>-->
  <p><img src="http://www.exagle.in/skin/frontend/default/exaglein/images/certified-seller-image.png"></p>
 </div>
  <!-- certified seller end -->

</div></div>