<div class="megaforum">
    <h1>Forum</h1>

    <?php
    $id = $this->getForumId();
    $forum = Mage::getModel('megaforum/forum')->getCollection();
    $fcount = $forum->count();
    ?>
    <?php
    $forums = Mage::getModel('megaforum/forum')->getCollection();
    ?>


    <?php if ($id==0) { ?>
        <h2>Benvenuti nel Forum di BurdaStyle!</h2>
        <h3>Scambia idee e consigli con gli utenti della Community</h3>

        <?php foreach($forum as $forums): ?>
            <div class="post-wrapper">
                <h2 class="post-title">
                    <a href="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forums->getForumId()));  ?>">
                        <?php echo $forums->getForumName(); ?>
                    </a>
                </h2>

                <?php $id = $forums->getForumId(); ?>
                <?php //$forum = Mage::getModel('megaforum/forum')->load($id); ?>


                <?php $_iterator = 0;
                $topic = Mage::getModel('megaforum/topic')->getCollection()->addFieldToFilter("forum_id",$id)->setPageSize(3);;
                ?>

                <table class="forum">

                    <thead>
                    <tr>
                        <th><?php echo $this->__('Topic'); ?></th>
                        <th><?php echo $this->__('Post'); ?></th>
                        <th class="reply"><?php echo $this->__('Ultimo Commento'); ?></th>
                    </tr>
                    </thead>

                    <?php
                    foreach($topic as $topics){
                        $customerName = Mage::getModel('customer/customer')->load($topics->getCreatedBy());
                        $activeTopics = Mage::getModel('megaforum/topic')->load($topics->getStatus());
                        ?>
                        <?php if($topics['status'] == "Active") { ?>
                            <tr class="<?php if( ++$_iterator == 3 ): ?>last<?php endif; ?>  <?php echo ($_iterator % 2 == 0) ? 'even' : 'odd'; ?>">

                                <?php $forumUser =  Mage::getModel('megaforum/forumuser')->getCollection()->addFieldToFilter("user_id",$customerName->getId())->getFirstItem(); ?>

                                <td width="40%">
                                    <a class="name" href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topics->getTopicId() ?>">
                                        <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($topics->getTopicName(),60, "...")); ?>
                                    </a>
                                    <span class="create">Creato da: <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>"><?php echo $customerName->getSevenlikeNickname(); ?></a></span>
                                </td>

                                <?php $posts = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id",$topics->getTopicId()); ?>
                                <td class="post-count"><?php echo $posts->count() ?></td>


                                <?php $replies = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id",$topics->getTopicId())->getLastItem();
                                $customerName = Mage::getModel('customer/customer')->load($replies->getPostedBy()); ?>

                                <?php if($replies['posted_by'] != NULL) { ?>
                                    <td>
                                        <!--                            TODO get image from user instead of forum-->
                                        <a class="img-avatar"  href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                                            <?php if($customerName->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($customerName->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
                                            <img src="<?= $img ?>" width="50" height="50">
                                        </a>
                                        <a class="post" href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topics->getTopicId(); ?>">
                                            <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($replies->getPostText(),60, "...")); ?>
                                        </a>
                                    <span class="create"><?php echo $this->formatDate($replies->getPostedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?>
                                        by <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>"><?php echo $customerName->getSevenlikeNickname(); ?></a></span>
                                    </td>
                                <?php } else { ?>
                                    <td><?php echo 'Nessun commento'?> </td>
                                <?php } ?>

                            </tr>
                        <?php
                        }

                    }
                    ?>
                </table>

            </div>

        <?php endforeach;
        ?>
    <?php } else { ?>

<?php $forum = Mage::getModel('megaforum/forum')->load($id); ?>
    <h2><?php echo $forum->getForumName(); ?></h2>
    <h3>Scambia idee e consigli con gli utenti della Community</h3>

<?php $_iterator = 0;
//$topic = Mage::getModel('megaforum/topic')->getCollection()->addFieldToFilter("forum_id",$id); ?>

    <script type="text/javascript">
        decorateGeneric(jQuery('order-info-tabs').select('LI'),['first','last']);
    </script>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $topic = $this->getCollection(); ?>
<?php echo $this->getToolbarHtml(); ?>
    <div class="post-wrapper">
        <table class="forum">

            <thead>
            <tr>
                <th><?php echo $this->__('Topic'); ?></th>
                <th><?php echo $this->__('Post'); ?></th>
                <th class="reply"><?php echo $this->__('Ultimo Commento'); ?></th>
            </tr>
            </thead>

            <?php
            foreach($topic as $topics){
                $customerName = Mage::getModel('customer/customer')->load($topics->getCreatedBy());
                $activeTopics = Mage::getModel('megaforum/topic')->load($topics->getStatus());
                ?>
                <?php if($topics['status'] == "Active") { ?>
                    <tr class="<?php if( ++$_iterator == sizeof($fcount) ): ?><?php endif; ?>  <?php echo ($_iterator % 2 == 0) ? 'even' : 'odd'; ?>">

                        <?php $forumUser =  Mage::getModel('megaforum/forumuser')->getCollection()->addFieldToFilter("user_id",$customerName->getId())->getFirstItem(); ?>

                        <td width="40%">
                            <a class="name" href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topics->getTopicId() ?>">
                                <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($topics->getTopicName(),60, "...")); ?>
                            </a>
                            <span class="create">Creato da: <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>"><?php echo $customerName->getSevenlikeNickname(); ?></a></span>

                        </td>

                        <?php $posts = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id",$topics->getTopicId()); ?>
                        <td class="post-count"><?php echo $posts->count() ?></td>


                        <?php $replies = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id",$topics->getTopicId())->getLastItem();
                        $customerName = Mage::getModel('customer/customer')->load($replies->getPostedBy()); ?>
                        <?php if($replies['posted_by'] != NULL) { ?>
                            <td>
                                <!-- TODO get image from user instead of forum -->
                                <a class="img-avatar" href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                                    <?php if($customerName->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($customerName->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
                                    <img src="<?= $img ?>" width="50" height="50">
                                </a>
                                <a class="post" href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topics->getTopicId() ?>">
                                    <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($replies->getPostText(),60, "...")); ?>
                                </a>
                                <span class="create"><?php echo $this->formatDate($replies->getPostedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> by <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>"><?php echo $customerName->getSevenlikeNickname(); ?></a></span>
                            </td>


                        <?php } else { ?>
                            <td><?php echo 'Nessun commento'?> </td>
                        <?php } ?>

                    </tr>
                <?php
                }
            }
            ?>
        </table>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml(); ?>
        </div>
    </div>

    <?php
    }
    ?>

</div>

<script language='javascript'>

    function slectBox(sel) {
        var value = sel.options[sel.selectedIndex].value;
        self.location=value;
    }

</script>

