<?php $id = $this->getRequest()->getParam("id"); ?>
<div id="button"  class="forum-buttons">

    <?php $topic = Mage::getModel('megaforum/topic')->load($id); ?>

        <a class="link-wishlist-add" href="<?php echo Mage::getUrl('megaforum/index/watchlist')."id/".$topic->getTopicId();  ?>">
            <?php echo $this->__('Aggiungi alla wishlist') ?>
        </a>


        <a class="link-right" href="<?php echo Mage::getUrl('megaforum/index/mywatchlist'); ?>">
            <?php echo $this->__('Vai alla wishlist') ?>
        </a>

        <?php if (Mage::getSingleton('customer/session')->isLoggedin()) : ?>
        <?php endif; ?>

        <!--<div class="space-search">
            <form method="post" action="<?php /*echo Mage::getUrl('megaforum/index/search'); */?>">
                <input type="text" name="query" value="Cerca" onblur="if(this.value == '') { this.value='Cerca'}" onfocus="if (this.value == 'Cerca') {this.value=''}">
                <button class="image-button" title="Search" type="submit"><span>Cerca nel Forum</span></button>
            </form>
        </div>-->

    <!-- <a href="<?php /*echo Mage::getUrl('megaforum/forum/rss'); */?>">
         <img src="<?php /*echo $this->getSkinUrl('images/rss-btn.png') */?>" />
     </a>-->
    <?php $forumx = Mage::getModel('megaforum/forum')->load($topic->getForumId()); ?>
        <button type="button" title="Scopri di più" class="button btn-new add-topic" onclick="setLocation('<?php echo Mage::getUrl('megaforum/index/mytopic', array('forum_id' => $forumx->getForumId()));?>')">
            <span><span><?php echo $this->__('Apri una nuova discussione') ?></span></span>
        </button>

        <button type="button" title="Scopri di più" class="button btn-new" onclick="setLocation('<?php echo Mage::getUrl('megaforum/index/mypost')."id/".$topic->getTopicId(); ?>')">
            <span><span><?php echo $this->__('Aggiungi un Post') ?></span></span>
        </button>


</div>