<div class="page-title">
    <h1>Forum: I miei post</h1>
</div>
<div class="box-account box-recent">

    <table id="my-orders-table" class="data-table">
        <?php if (count($post)){ ?>
        <thead>
        <tr class="first last">
            <th style="width: 20%">Forum</th>
            <th style="width: 25%">Argomenti</th>
            <th style="width: 40%">Post</th>
            <th style="width: 15%">Inviato il</th>
        </tr>
        </thead>
        <tbody>

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php $post = $this->getCollection(); ?>
        <?php //todo check if pager needed ?>
        <?php echo $this->getPagerHtml(); ?>

        <?php foreach ($post as $posts) {
                ?>
                <?php /* Dan Nistor - view posts only for user created posts */ ?>
                <?php $customerSession = Mage::getSingleton('customer/session'); ?>
                <?php if ($customerSession->isLoggedIn()) : ?>
                    <?php if ($posts->getPostedBy() == $customerSession->getId()) : ?>

                        <?php
                        //Dan Nistor - no need to load customer
                        //$customerName = Mage::getModel('customer/customer')->load($posts->getPostedBy());
                        $topic = Mage::getModel('megaforum/topic')->load($posts->getTopicId());
                        $forum = Mage::getModel('megaforum/forum')->load($topic->getForumId());
                        ?>
                        <tr class="first last odd">
                            <td>
                                <a href="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forum->getForumId()));  ?>">
                                    <?php echo $forum->getForumName(); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topic->getTopicId() ?>" clas="name" >
                                    <?php echo $topic->getTopicName(); ?>
                                </a>
                            </td>
                            <td><?php echo $posts->getPostText(); ?> </td>
                            <td><?php echo $this->formatDate($posts->getPostedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> </td>
                            <!--                        <td>--><?php //echo $customerName->getFirstname(); ?><!-- </td>-->
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            <?php } ?>
        <?php } else { ?>
            <tr class="vuoto">
                <td colspan="4" >
                    <p style="margin: 0px 0 40px 0;">Nessun post inserito</p>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <script type="text/javascript">
        decorateTable('my-orders-table')
    </script>
</div>



