<?php
$forum = Mage::getModel('megaforum/forum')->getCollection();
$fcount = $forum->count();

$id = $this->getRequest()->getParam("id");
$topic = Mage::getModel('megaforum/topic')->load($id);
$viewcount = $topic->getViews();
$topic->setViews($viewcount + 1)->save();

$watchlist = Mage::getModel('megaforum/watchlistsingle')->getCollection()->count();
?>
<div class="megaforum">
    <h1><?php echo $this->__('Forum') ?></h1>
    <?php $forumss = Mage::getModel('megaforum/forum')->load($topic->getForumId()); ?>
    <h2><?php echo $forumss->getForumName(); ?></h2>
    <h3><?php echo $topic->getTopicName(); ?></h3>
    <script type="text/javascript">
        decorateGeneric($('order-info-tabs').select('LI'), ['first', 'last']);
    </script>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $post = $this->getCollection(); ?>
    <?php echo $this->getToolbarHtml(); ?>

    <!--<div class="postTitle com"><a name="commentBox" ></a>
        <h2>Commenti</h2>
    </div>-->

    <?php $_iterator = 0; ?>

    <?php
        $firstPost = $this->getFirstPost();
        $customerName = Mage::getModel('customer/customer')->load($firstPost->getPostedBy());
        //$activePosts = Mage::getModel('megaforum/post')->load($firstPost->getStatus());
    ?>
    <div class="commentWrapper first">
        <div class="commentDetails">
            <h4>
                <span>
                    <?php //echo $this->formatDate($firstPost->getPostedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> by
                    <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                        <?php echo $customerName->getSevenlikeNickname(); ?>
                    </a>
                </span>
            </h4>
            <a class="link-private" href="<?php echo Mage::getUrl('megaforum/index/privatemsg') . "id/" . $firstPost->getPostId() ?>">
                <?php echo $this->__('Invia Messaggio Privato') ?>
            </a>

            <div class="img">
                <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                    <?php if($customerName->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($customerName->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
                    <img src="<?= $img ?>" width="150" height="150">
                </a>
            </div>

        </div>

        <div class="commentContent">
            <?php echo $firstPost->getPostText(); ?>
            <?php /* Dan Nistor - edit & delete posts only if registered and only for the user who created the post */ ?>
            <?php $customerSession = Mage::getSingleton('customer/session'); ?>
            <?php if ($customerSession->isLoggedIn()) : ?>
                <?php if ($firstPost->getPostedBy() == $customerSession->getId()) : ?>
                    <ul class="links a-right">
                        <li>
                            <a href="<?php echo Mage::getUrl('megaforum/index/delete') . "id/" . $firstPost->getPostId() ?>"><?php echo $this->__('Elimina') ?></a></strong>
                            <span class="separator"> |</span>
                        </li>
                        <li>
                            <button class="button btn-read" onclick="setLocation('<?php echo Mage::getUrl('megaforum/index/edit') . 'id/' . $firstPost->getPostId() ?>')">
                                <span><span><?php echo $this->__('Modifica Post') ?></span></span>
                            </button>

                        </li>

                    </ul>
                <?php endif; ?>
            <?php endif; ?>
            <div class="social">
                <p><span>Ti piace?</span> Condividilo!</p>
                <ul>
                    <li><a class="fb" href="http://www.facebook.com/sharer.php?u=<?php echo $firstPost->getAddress(); ?>" onclick="window.open(this.href); return false;"></a></li>
                    <li><a class="tw" href="https://twitter.com/share?url=<?php echo $firstPost->getAddress(); ?>" onclick="window.open(this.href); return false;"></a></li>
                    <li><a class="gp" href="https://plus.google.com/share?url=<?php echo $firstPost->getAddress(); ?>" onclick="window.open(this.href); return false;"></a></li>
                    <li><a class="pt" href="http://pinterest.com/pin/create/button/?url=<?php echo $firstPost->getAddress(); ?>&description=&media=" onclick="window.open(this.href); return false;"></a></li>
                </ul>
            </div>
        </div>
    </div>

    <?php
    foreach ($post as $posts) {
        $customerName = Mage::getModel('customer/customer')->load($posts->getPostedBy());
        $activePosts = Mage::getModel('megaforum/post')->load($posts->getStatus());
        ?>

        <?php if ($posts['status'] == "Active") { ?>
        <?php
            $forumUser = Mage::getModel('megaforum/forumuser')
                ->getCollection()
                ->addFieldToFilter("user_id", $customerName->getId())
                ->getFirstItem();
        ?>
                <div class="commentWrapper <?php if (++$_iterator == sizeof($fcount)): ?><?php endif; ?>">
                    <div class="commentDetails">
                        <div class="img">
                            <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                                <?php if($customerName->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($customerName->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
                                <img src="<?= $img ?>" width="50" height="50">
                            </a>
                        </div>
                        <div class="det">
                            <h4 class="username">
                                    <span>
                                        <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customerName->getId() ?>">
                                            <?php echo $customerName->getSevenlikeNickname(); ?>
                                        </a>
                                    </span>
                            </h4>
                            <span><?php echo $this->formatDate($posts->getPostedAt(), Mage::getStoreConfig('blog/blog/dateformat')); ?></span></br>

                            <a class="link-private" href="<?php echo Mage::getUrl('megaforum/index/privatemsg') . "id/" . $posts->getPostId() ?>"><?php echo $this->__('Invia Messaggio Privato') ?></a>

                        </div>
                    </div>

                    <div class="commentContent">
                        <?php echo $posts->getPostText(); ?>
                        <?php /* Dan Nistor - edit & delete posts only if registered and only for the user who created the post */ ?>
                        <?php $customerSession = Mage::getSingleton('customer/session'); ?>
                        <?php if ($customerSession->isLoggedIn()) : ?>
                            <?php if ($posts->getPostedBy() == $customerSession->getId()) : ?>
                                <ul class="links a-right">
                                    <li>
                                        <a href="<?php echo Mage::getUrl('megaforum/index/delete') . "id/" . $posts->getPostId() ?>"><?php echo $this->__('Elimina') ?></a></strong>
                                        <span class="separator"> |</span>
                                    </li>
                                    <li>
                                        <button class="button btn-read" onclick="setLocation('<?php echo Mage::getUrl('megaforum/index/edit') . 'id/' . $posts->getPostId() ?>')">
                                            <span><span><?php echo $this->__('Modifica Post') ?></span></span>
                                        </button>

                                    </li>

                                </ul>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php
        }
    }
    ?>

    <button class="button btn-reply" onclick="setLocation('<?php echo Mage::getUrl('megaforum/index/mypost') . "id/" . $topic->getTopicId(); ?>')">
        <span><span><?php echo $this->__('Aggiungi Post') ?></span></span>
    </button>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml(); ?>
    </div>
</div>


<script language='javascript'>

    function slectBox(sel) {
        var value = sel.options[sel.selectedIndex].value;
        self.location = value;
    }

</script>

