<?php // @see MG_Megaforum_Block_Profiletopic ?>

<div class="profile-user-topic">
    <h2><?php echo $this->__('Topic'); ?></h2>
    <?php $userTopicCollection = $this->getUserTopicCollection(); ?>
    <?php echo $this->getPagerHtml(); ?>

    <?php if (count($userTopicCollection)){ ?>
    <table class="data-table">
        <thead>
        <tr class="first last">
            <th><?php echo $this->__('Forum'); ?></th>
            <th><?php echo $this->__('Topic'); ?></th>
            <th class="post-count"><?php echo $this->__('Totale Post'); ?></th>
            <th class="post-count"><?php echo $this->__('Creato il'); ?></th>
        </tr>
        </thead>


        <?php foreach ($userTopicCollection as $topic) : ?>
            <?php $forum = Mage::getModel('megaforum/forum')->load($topic->getForumId()); ?>

            <tr>
                <td>
                    <a href="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forum->getForumId()));  ?>">
                        <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($forum->getForumName(),60, "...")); ?>
                    </a>
                </td>
                <td>
                    <a href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topic->getTopicId() ?>" clas="name" >
                        <?php echo strip_tags( $text = Mage::helper('core/string')->truncate($topic->getTopicName(),60, "...")); ?>
                    </a>
                </td>

                <td class="post-count">
                    <?php $postCollection = Mage::getModel('megaforum/post')
                        ->getCollection()
                        ->addFieldToFilter('topic_id', $topic->getTopicId());
                    ?>
                    <?php echo $postCollection->getSize() ?>
                </td>
                <td class="post-count"><?php echo $this->formatDate($topic->getCreatedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> </td>

            </tr>
        <?php endforeach; ?>
    </table>
    <?php } else { ?>
        <p style="margin: 0px 0 40px 0;">L'utente non ha pubblicato nessun argomento/discussione</p>
    <?php } ?>
</div>