<h2><?php echo $this->__('Rispondi al messaggio privato') ?></h2><br>

<div class="mega-forum">
    <?php
    $id = $this->getRequest()->getParam("id");
    $privatemsg = Mage::getModel('megaforum/privatemsg')->load($id);
    $customerName = Mage::getModel('customer/customer')->load($privatemsg->getSentFrom());
    $forumUser = Mage::getModel('megaforum/forumuser')->getCollection()->addFieldToFilter("user_id", $customerName->getId())->getFirstItem();
    ?>

    <form id="megaforum-form" enctype="multipart/form-data" method="post"
          action="<?php echo Mage::getUrl('megaforum/index/myreply', array('id' => $id)) ?>">

        <div style="float:left;  margin-left:30px; background:#f7f7e9;padding:5px; margin-right:30px;">
            <img src="<?php echo Mage::getBaseUrl('media') . $forumUser->getImage(); ?>" alt="" width="100" height="100"
                 title="" style="float:left;  	border:2px solid #777575;"/><br>

            <table id="my-orders-table-send" class="data-table">
                <colgroup>
                    <col width="1"></col>
                    <col width="1"></col>
                    <col width="1"></col>
                    <col width="1"></col>
                </colgroup>
                <thead>
                <tr class="first last">
                    <th><?php echo $this->__('Subject') ?></th>
                    <th><?php echo $this->__('Inviato da') ?></th>
                    <th><?php echo $this->__('Data di invio') ?></th>
                    <th><?php echo $this->__('Message') ?></th>

                </tr>
                </thead>
                <tbody>

                    <tr class="first last odd topics">
                        <td><?php echo $privatemsg->getSubject(); ?> </td>
                        <td><?php echo $customerName->getFirstname();; ?> </td>
                        <td><?php echo $privatemsg->getSentDate(); ?> </td>
                        <td><?php echo $privatemsg->getMessage(); ?> </td>
                        <td><?php echo $this->formatDate($privatemsg->getSentDate(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> </td>
                    </tr>
                </tbody>
            </table>

        </div>

        <div class="private-msg" style="float:left; width:608px;">
            <div>
                <label for="title_field"><strong><?php echo $this->__('Subject') ?><strong><span class="required">*</span></label><br>
                <input id="subject" class="required-entry" type="text" value="" style="width: 630px;"
                       name="subject"></input>
            </div>

            <div>
                <label for="content_field"><strong><?php echo $this->__('Message') ?><strong><span class="required">*</span></label><br>
                <textarea id="message" class="required-entry" style="width: 450px;" rows="10" cols="53"
                          name="message"></textarea><br><br>
            </div>

            <div class="button-set">
                <input class="topic-btn" type="submit" value="Invia Messaggio"></input>
            </div>

        </div>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('megaforum-form', true);
    //]]>
</script>

<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "textareas",
        theme: "advanced",
        relative_urls: false,
        plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,

        // Skin options
        skin: "o2k7",
        skin_variant: "silver",

        // Example content CSS (should be your site CSS)
        content_css: "css/example.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url: "js/template_list.js",
        external_link_list_url: "js/link_list.js",
        external_image_list_url: "js/image_list.js",
        media_external_list_url: "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values: {
            username: "Some User",
            staffid: "991234"
        }
    });
</script>



