<?php
/**
 * @category	design
 * @package		base_default
 * @author      Felix Moche <felix@kreativkonzentrat.de>
 * @copyright	2012-2013 Kreativkonzentrat GbR
 */
?>
<h4><?php echo $this->__('Glossary') ?></h4>
<?php
echo $this->getChildHtml('glossary_letter_navigation');
$collection = $this->getGlossary();
foreach ($collection as $item) :?>
	<div class="glossary_entry">
		<h2><a href="<?php echo $item->getUrl(); ?>"><?php echo $item->getTitle(); ?></a></h2>
	</div>
<?php endforeach; ?> 