<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar');

?>
<div class="blogcontainer">
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <?php $img= Mage::getBaseUrl('media').$post->getFotopost(); ?>
        <div class="leftBlog">
            <img src="<?php echo $img; ?>" width="205" height="273" />
        </div>
        <div class="rightBlog">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                <h4>
                    <?php $postCats = $post->getCatsData(); ?>
                    <?php if (!empty($postCats)): ?>
                        <?php foreach ($postCats as $id => $catData): ?>
                            <a href="<?php echo $catData['url']; ?>" class="cat-<?php echo $id; ?>"><?php echo $catData['title']; ?></a>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php echo Mage::helper('blog')->__(''); ?>
                    <?php endif; ?>
                <?php echo $this->__('Pubblicato il'); ?> <?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> <?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></h4>
            </div>
            <div class="postContent">
               <?php 
                    if(strlen($post->getPostContent()) > 650) {
                        echo substr($post->getPostContent(), 0, 650)."...";
                        echo $this->_getReadMoreLink($post);
                     } else {
                        echo $post->getPostContent(); 
                     }
               ?>
               <?php if ($this->getCommentsEnabled()): ?>
                    <a href="<?php echo $post->getAddress(); ?>#commentBox" class="commenti">Commenti <small><?php echo $post->getCommentCount(); ?></small></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="spaceBtwnPost"></div>
<?php endforeach; ?>
</div>
<div class="toolbar-bottom">
    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
</div>
