<div class="block block-blog">
    <div class="block-title">
        <h2 class="blog">ARGOMENTI<small></small></h2>
    </div>
    <div class="block-content">
        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="menu-categories">
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>" class="cat-<?= $cat->getId(); ?>"><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
</div>