<?php if ($posts = $this->getRecent()): ?>

    <div class="block block-mostRead">

        <h2 class="mostRead">Articoli <small>più letti</small></h2>
        <ul>
            <?php foreach ($posts as $post): ?>
                <?php $img= Mage::getBaseUrl('media').$post->getFotopost(); ?>
                <li>
                    <div class="img">
                        <img src="<?php echo $img; ?>" width="112" height="150" />
                    </div>
                    <div class="det">
                        <a href="<?php echo $post->getAddress(); ?>" class="title"><?php echo $post->getTitle(); ?></a>
                        <p class="dati">
                            <?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?>
                            <br><?php echo $this->__("By"); ?> <span class="writer"><?php echo $post->getUser(); ?></span>
                        </p>

                        <?php echo substr(strip_tags($post->getPostContent()), 0, 100) . "..."; ?>
                        <!--<p class="comm"><?php //echo $post->getComments(); ?> commenti</p>-->
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <hr class="separator-x">
    </div>
<?php endif; ?>