<p><a href="<?php echo $this->url(
    array(
        'controller' => 'slide',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>
 
Slides Times Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->slide_time_id) ?></dt>
    <dd><?php echo $this->escape($entry->slide_id) ?></dd>
    <?php endforeach ?>
</dl>