
<h1>Mega Forum</h1><br>
<div class="mega-forum">
<?php  
$id = $this->getRequest()->getParam("id");
$post = Mage::getModel('megaforum/post')->load($id); 
$topic = Mage::getModel('megaforum/topic')->load($post->getTopicId());
?>

<form id="megaforum-form" enctype="multipart/form-data" method="post" action="<?php echo Mage::getUrl('megaforum/index/editme')?>">

<div>
<!--<label for="title_field"><strong>TITLE</strong><span class="required"> * </span></label><br>-->
<input id="topic_id" class="input-text required-entry" type="hidden" value="<?php echo $topic->getTopicId();?>" style="width: 450px;" name="topic_id"></input>
</div>

<div>
<label for="content_field"><strong>POST<strong><span class="required">*</span></label><br>
<textarea id="post_text" class="required-entry" style="width: 450px;" rows="10" cols="53" name="post_text"><?php echo $post->getPostText();?></textarea><br><br>
</div>

<input id="post_id" type="hidden" value="<?php echo $post->getpostId();?>" style="width: 450px;" name="post_id"></input>
<input id="posted_at" type="hidden" value="<?php echo $post->getPostedAt();?>" style="width: 450px;" name="posted_at"></input>
<input id="posted_by" type="hidden" value="<?php echo $post->getPostedBy();?>" style="width: 450px;" name="posted_by"></input>
<input id="position" type="hidden" value="<?php echo $post->getPosition();?>" style="width: 450px;" name="position"></input>
<input id="status" type="hidden" value="<?php echo $post->getStatus();?>" style="width: 450px;" name="status"></input>

<div class="button-set">
<input class="topic-btn upload-btn" type="submit" value="Save post"></input>
</div>

<!--<div class="button-set"><a class="left" href=""></a>
<button class="image-button" type="submit"><span><span>Save post</span></span></button>
</div>-->

</form>
</div>

<script type="text/javascript">
   //<![CDATA[
    var dataForm = new VarienForm('megaforum-form', true);
   //]]> 
</script>