<h2>My Forum Posts</h2><br>

<div class="box-account box-recent">

<table id="my-orders-table" class="data-table"><colgroup><col width="1"></col><col width="1"></col><col></col><col width="1"></col><col width="1"></col><col width="1"></col></colgroup>
<thead><tr class="first last">
<th>FORUM NAME</th>
<th>TOPIC NAME</th>
<th>POST</th>
<th>POSTED AT</th>
<th>POSTED BY</th>
</tr>
</thead>
<tbody>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $post = $this->getCollection(); ?>
<?php echo $this->getPagerHtml(); ?>

<?php
foreach($post as $posts)
{
$customerName = Mage::getModel('customer/customer')->load($posts->getPostedBy());
$topic = Mage::getModel('megaforum/topic')->load($posts->getTopicId()); 
$forum = Mage::getModel('megaforum/forum')->load($topic->getForumId()); 
?>
<tr class="first last odd">
<td><?php echo $forum->getForumName();?> </td>
<td><?php echo $topic->getTopicName();?> </td>
<td><?php echo $posts->getPostText();?> </td>
<td><?php echo $posts->getPostedAt();?> </td>
<td><?php echo $customerName->getFirstname();?> </td>
</tr>
<?php } ?>
</tbody>
</table>

<script type="text/javascript">
      decorateTable('my-orders-table')
</script>
</div>



