<h2>My Forum Topics</h2><br>

<div class="box-account box-recent">

<table id="my-orders-table" class="data-table"><colgroup><col width="1"></col><col width="1"></col><col></col><col width="1"></col><col width="1"></col><col width="1"></col></colgroup>
<thead><tr class="first last">
<th>FORUM NAME</th>
<th>TOPIC NAME</th>
<th>CREATED AT</th>
<th>CREATED BY</th>
<th>TOTAL POSTS</th>
</tr>
</thead>
<tbody>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $topic = $this->getCollection(); ?>
<?php echo $this->getPagerHtml(); ?>

<?php 
foreach($topic as $topics)
{
$customerName = Mage::getModel('customer/customer')->load($topics->getCreatedBy());
$post = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id",$topics->getTopicId());
$forum = Mage::getModel('megaforum/forum')->load($topics->getForumId()); 
?>
<tr class="first last odd topics" >
<td><?php echo $forum->getForumName();?> </td>
<td><?php echo $topics->getTopicName();?> </td>
<td><?php echo $topics->getCreatedAt();?> </td>
<td><?php echo $customerName->getFirstname();?> </td>
<td><?php echo $post->count();?> </td>
</tr>
<?php } ?>
</tbody>
</table>

<script type="text/javascript">
      decorateTable('my-orders-table')
</script>
</div>



