<div class="megaforum">
<h1>Mega Forum</h1><br><br><br>

<?php 
$forum = Mage::getModel('megaforum/forum')->getCollection(); 
$fcount = $forum->count();
?>

<div style="width:300px;" >

<table>
		<tr>
			<td class="list">
				Go To : &nbsp;
			</td>
			<td>
				<select class="selection" onchange="slectBox(this)" id='selectedForum'>  
						  <option value="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => 0));  ?>">Index</option>			
						  <?php foreach($forum as $forums){ ?>
						  <option id="<?php echo $forums->getForumId(); ?>" value="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forums->getForumId()));  ?>"
						  <?php echo $forums->getForumName(); ?> </option>					 
						  <?php
						  }
						  ?>
				</select>
			</td>
		</tr>
</table>
</div><br>

<div>

<form method="post" action="search.php">
	<table>
		<tbody><tr>
			<td width="445">
				<h3>Search Results</h3>
			</td>
			<td>
				<input type="text" name="query" value="SEARCH" onblur="if(this.value == '') { this.value='SEARCH'}" onfocus="if (this.value == 'SEARCH') {this.value=''}">      
				<button  class="image-button" title="Search" type="submit"><span>Search Forum</span></button>			
			</td>
				</tr>
	</tbody></table>
</form>
</div>

<?php
 $query = $_POST['query']; 
?>

<div class="topic-name">

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $result = $this->getCollection();  
	  $result_count = $result->count(); ?>
<?php echo $this->getToolbarHtml(); ?>

<table class="forum">	
<tbody>

<?php $_iterator = 0; ?>
<?php if($result_count != 0) { ?>
<?php
foreach($result as $results){ 
?>
		<tr class="<?php if( ++$_iterator == sizeof($fcount) ): ?><?php endif; ?>  <?php echo ($_iterator % 2 == 0) ? 'even' : 'odd'; ?>">
										
			<td><a href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$results['topic_id'] ?>"><?php  echo "<p><h3>".$results['topic_name']."</h3></a>".$results['message']."</p>";?></td>			

		</tr>	
<?php
}
?>
<?php
}
else {  
?>
		<tr class="<?php if( ++$_iterator == sizeof($fcount) ): ?><?php endif; ?>  <?php echo ($_iterator % 2 == 0) ? 'even' : 'odd'; ?>">
										
					 <td class="a-center"><?php  echo "No Results Matches Search " ."<p><h3>"."'$query'"."</h3></p>"; ?></td>			

		</tr>
<?php
}
?>
		
</tbody>
</table></div>
</div>



<script language='javascript'>

function slectBox(sel) {
var value = sel.options[sel.selectedIndex].value; 
self.location=value;
}

</script>