<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
        <ul class="cats">
            <li><h4><?php echo Mage::helper('blog')->__('Argomenti'); ?></h4></li>
        <?php $cats = $this->getCategories(); ?>
        <?php foreach ($cats as $cat): ?>
            <li><a href="<?php echo $cat->getAddress(); ?>" class="cat-<?= $cat->getId(); ?>"><?php echo $cat->getTitle(); ?></a></li>
        <?php endforeach; ?>
        </ul>
<?php endif; ?>


<div class="ultime-news">
    <h4 class="title">Le ultime news</h4>
<?php
    $cats = Mage::getModel("blog/cat")->getCollection()->setPageSize(4);
    $i = 1;
    foreach($cats as $c)
    {
        if($i==4) $st = "margin-left:0;"; else $st = "";
        if($i==1) $hide = "class='last'"; else $hide = "";
        echo "<ul style='width:150px;margin-left:25px;float:right;".$st."' ".$hide.">";

        $collection = Mage::getModel('blog/blog')->getCollection()
            ->addPresentFilter()
            ->addEnableFilter(AW_Blog_Model_Status::STATUS_ENABLED)
            ->addStoreFilter()
            ->addCatFilter($c->getCatId())
            ->joinComments()
            ->setOrder('created_time', 'desc')
            ->setPageSize(1)
        ;

        foreach($collection as $p)
        {
            $url = $this->getBlogUrl(
                null,
                array(
                    ''  => $c->getIdentifier(),
                    '' => $p->getIdentifier()
                )
            );
            print '<li class="titolo-news" style="margin-bottom:5px"><a href="' . $url . '">' . $p->getTitle() . '</a></li>';
            print '<li><a href="' . $url . '"><img src="' . Mage::getBaseUrl('media').$p->getFotopost() . '" style="max-width: 150px;max-height: 185px;" /></a></li>';
            print '<li style="margin-top:3px;">da: <h4 style="display: inline-block;" class="cat-' . $c->getId() . '">' . $c->getTitle() . '</h4></li>';
            print '<li><a class="link-right" style="float: right;margin-top: 10px;padding-right: 20px;" href="' . $url . '">Leggi</a>';
        }
        $i++;
        echo "</ul>";
    }
?>
</div>