<div class="eventi">
    <h2 class="events"><?php echo $this->__("EVENTS") ?> <small><?= $this->__("In calendario!"); ?></small></h2>
    <?php
        $collection = $this->getPosts()->clear();
        $collection
            ->addFieldToFilter("data_evento", array("from" => date("Y-m-d")))
            ->setOrder('data_evento', 'asc')
            ->addCatFilter(2)
            ->setPageSize(8)
        ;
        $collection->getSelect()->group('post_id');
    ?>
    <?php if (count($collection)): ?>
        <?php $i = 1; ?>
        <?php foreach ($collection as $post): ?>
            <?php ($i%2==0) ? $right = 'right' : $right = ''; ?>
            <div class="evento <?= $right; ?>">
                <?php setlocale(LC_TIME, 'it_IT'); ?>
                <?php $date = strtotime($post->getDataEvento()); ?>
                <?php $date = strftime('<span class="month">%h</span> <span class="day">%d</span>', $date); ?>
                <div class="data"><?php echo $date; ?></div>
                <div class="postWrapper">
                    <div class="postTitle">
                        <a href="/news/<?php echo $post->getIdentifier(); ?>/" class="open ms"><?php echo $post->getTitle(); ?></a>
                    </div>
                    <div class="postDesc">
                        <p><?php echo $post->getShortContent(); ?></p>
                    </div>
                    <p class="luogo"><?php echo $post->getLuogoEvento(); ?></p>
                    <p class="readmore"><a href="/news/<?php echo $post->getIdentifier(); ?>/"><?= $this->__('Leggi'); ?></a></p>
                </div>
            </div>
            <?php $i++; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
    <?php endif; ?>
</div>