
<ul class="sidebar-category-riviste">
    <dt>Categoria</dt>
    <?php
    $obj = new Mage_Catalog_Block_Navigation();
    $storeCategories = $obj->getStoreCategories();
    Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
    foreach ($storeCategories as $_category):
    ?>
    <?php if($_category->getId() == 3) :?>
    <li>
        <!--<strong><?php /*echo $_category->getName(); */?></strong>-->
        <?php $categoryChildren = $_category->getChildren(); ?>
        <?php if($categoryChildren->count()) : ?>
            <ul>
                <?php foreach($categoryChildren as $_categoryChild) : ?>
                    <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId());?>
                    <?php $categoryGrandchildren=$_categoryChild->getChildren(); ?>
                    <?php $currentCategoryId===$_categoryChild->getId() ? $bold="class=\"current\"" : $bold='';?>
                    <li <?php echo $bold ?> >
                        <?php
/*                            echo '<a href="' . $_categoryChildModel->getUrl() . '"' . $bold . '>' .  $_categoryChild->getName() . '(' . $_categoryChildModel->getProductCollection()->count() . ')</a>';
                        */?>
                        <?php
                        echo '<a  href="' . $_categoryChildModel->getUrl() . '">' .  $_categoryChild->getName() . '</a>';
                        ?>
                    </li>
                    <?php if($categoryGrandchildren->count()) : ?>
                        <?php foreach($categoryGrandchildren as $_categoryGrandchild) : ?>
                            <?php $_categoryGrandchildModel = Mage::getModel('catalog/category')->load($_categoryGrandchild->getId());?>
                            <?php $currentCategoryId===$_categoryGrandchild->getId() ? $bold="class=\"current\"" : $bold='';?>
                            <li <?php echo $bold ?>>
                                <?php /*
                                    echo '&emsp;' . '<a href="' . $_categoryGrandchildModel->getUrl() . '">' .  $_categoryGrandchild->getName() . '(' . $_categoryGrandchildModel->getProductCount() . ')</a>';
                                */?>
                                <?php
                                    echo '<a class="due" href="' . $_categoryGrandchildModel->getUrl() . '">' .  $_categoryGrandchild->getName() . '</a>';
                                ?>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </li>
    <?php endif; ?>
    <?php endforeach ?>
</ul>