<script type="text/javascript" src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ?>/video/video.js"></script>
<?php
    $login= Mage::getStoreConfig('video/video_group/login');
    $width  = Mage::getStoreConfig('video/video_group/width');
    $height = Mage::getStoreConfig('video/video_group/height');
    $strech = Mage::getStoreConfig('video/video_group/stretch');
    $autostart = Mage::getStoreConfig('video/video_group/autostart');
    $controls = Mage::getStoreConfig('video/video_group/controls');
    $controlbar = Mage::getStoreConfig('video/video_group/controlbar');

    $autostart= $autostart == 1 ? 'true' : 'false';
    $controls= $controls == 1 ? 'true' : 'false';
    $controlbar= $controlbar == 1 ? 'over' : 'none';

    $flag=1;
    $_product = $this->getProduct();
    $_mediaserver_helper = $this->helper('mediaserver');
    $is_video_bought = $_mediaserver_helper->isVideoBought($_product->getId());
    if (!$is_video_bought) $is_video_bought = strtoupper(substr($_product->getAttributeText("pagamento"), 0, 1)) == "G";
 ?>

 <?php if($login): ?><?php if(!Mage::helper('customer')->isLoggedIn()): $flag=0; endif; ?><?php endif; ?>

  <?php if($flag): ?>

        <?php    $_product = $this->getProduct();?>

        <?php if( $video = $_product->getVideoPreview() ){ ?>
        <?php
             $video_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."blfa_files/".$video;
             $swf_url   = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."video/player.swf";
        ?>
        <div class="product_video" >

        <?php if( file_exists( getcwd() .'/media/blfa_files/'. $video ) ){ ?>


         <!--<div class="video" id="vid" <?php //if($autostart=='true'): ?>style=display:block <?php //endif; ?> >
            <div class="a_container"> <a href="#" onclick="stopVideo()" style="display:none" id="close_a"> <img src="<?php //echo $this->getSkinUrl('images/video/close.jpg') ?>" width="18"/> </a></div>
            <div id="container" >Loading the player ...</div>
        </div> -->
        <div class="info-video-container">          
          <div class="video-preview"><?php echo $this->__('Video Preview'); ?></div>
          <div class="video-title"><?php echo $_product->getName() ?></div>

          <?php if ($is_video_bought and $_mediaserver_helper->hasProductCompleteVideo($_product->getId())): ?>
          <div class="add-to-box 4">
            <a href="#" onclick="jQuery('#slOpenVideoIframe').show();autoplayvideo();return false;" id="slOpenVideo"><?= $this->__("Visualizza il video completo") . "&nbsp;<span>&raquo;</span>" ?></a>
          </div>
                  <div class="close-slOpenVideoIframe"><img src="<?php echo $this->getSkinUrl('images/close-video.png') ?>"></div>
          <iframe id="slOpenVideoIframe" src="http://<?= $_mediaserver_helper->getMediaServerUrl() . "/video/play?product_id=" . $_product->getId() ?>" width="100%" height="100%" style="position:absolute;top:0;left:0;display:none;z-index:10000;border:none;"></iframe>
          <script type="text/javascript">
            document.domain = "burdastyle.it";
            function autoplayvideo () {
              try {
                if (typeof jQuery("#slOpenVideoIframe")[0].contentWindow.videojs == "function") {
                  jQuery("#slOpenVideoIframe")[0].contentWindow.videojs("videojs_id").play();
                  setTimeout(function () {
                    jQuery("#slOpenVideoIframe")[0].contentWindow.videojs("videojs_id").play();
                  }, 200);
                } else {
                  setTimeout(autoplayvideo, 200);
                }
              } catch (e) {
                setTimeout(autoplayvideo, 200);
              }
            }
            
            <?php if (@$_REQUEST["play"]): ?>
            jQuery(function () {
              jQuery("#slOpenVideo").click();
              autoplayvideo();
            });
            <?php endif ?>
          </script>
        <?php endif ?>





          <div class="video-description"><?php echo $_product->getShortDescription() ?></div>
        </div>


        <video width="100%" height="auto" controls id="video-slide" class="video-slide" >
            <source src="<?php echo $video_url ?>" data-src="<?php echo $video_url ?>" type="video/mp4">
        </video>

        <?php } else { ?>
             <script> alert("video <?php echo $video ?> not found");</script>
        <?php } ?>
        </div>
        <?php } ?>
    <?php endif ;?>


 <!--<script type="text/javascript">
 <?php /*echo 'jQuery(function () {
    jwplayer("container").setup({
        flashplayer: "'. $swf_url .'",
        autostart: '. $autostart .',
        controlbar: "'. $controlbar .'",
        file: "'.  $video_url .'",
        displaytitle: true,
        title: "'.$_product->getName().'",
        description: "'.$_product->getShortDescription().'",
        image: "'.$_product->getImageUrl().'",
        //type: "mp4",
        controls:'.  $controls .',
      logo: {
                hide: true,
                position: "top-left"

        },
                width: "80%",
                height: "100%",
                stretching:"'. $strech .'",
                //screencolor:"FFFFFF",
                //fallback:false,

               plugins: {
                  "viral-2": {"oncomplete":"False","onpause":"False","functions":"All"}
               },
                events: {
                onComplete: function() {document.getElementById("vid").style.display="none" ;}
                }
    });
 });
 </script>' */?>-->

