<?php
/**
 * @category	design
 * @package		base_default
 * @author      Felix Moche <felix@kreativkonzentrat.de>
 * @copyright	2012-2013 Kreativkonzentrat GbR
 */
?>
<?php $item = $this->getGlossary(); ?>

<?php if ($item) : ?>
    <h1><?php echo $item->getTitle(); ?></h1>
<div class="glossary_entry">

	<p><?php echo $item->getGlossaryContent(); ?></p>
</div>
<?php else : ?>
	<h1><?php echo __('Glossary entry could not be found.');?></h1>
<?php endif; ?>