<?php
echo $this->getChildHtml('glossary_letter_navigation');
$collection = $this->getGlossary();

$glossary_id = $this->getRequest()->getParam('id');
$letter = array_keys($this->getRequest()->getParams());

?>

<h1>Lettera <?php echo $letter[0] ?></h1>

<ul class="glossary_entry">
    <?php foreach ($collection as $item) : ?>

            <li><a href="<?php echo $item->getUrl(); ?>"><?php echo $item->getTitle(); ?></a></li>

    <?php endforeach; ?>
</ul>