<div class="voluti">
<h2 class="wanted"><?= $this->__("SHOP") ?> <small><?= $this->__("Scelti per voi da acquistare!"); ?></small></h2>
<?php

    $_productCollection = Mage::getModel("Mage_Catalog_Model_Resource_Product_Collection");

    $_productCollection = $_productCollection
        ->addAttributeToSelect("vetrina")
        ->addAttributeToSelect("sku")
        ->addAttributeToSelect("name")
        ->addAttributeToSelect("size")
        ->addAttributeToSelect("price")
        ->addAttributeToSelect("special_price")
        ->addAttributeToSelect("prezzo_visibile")
        ->addAttributeToSelect("prodotto_nuovo")
        ->addAttributeToSelect("pagamento")
        ->addAttributeToSelect("livello")
        ->addAttributeToSelect("thumbnail")
        ->addAttributeToFilter("vetrina", 1)
        ->setPageSize(3)
		->addFinalPrice()
    ;
$_productCollection->getSelect()->order(new Zend_Db_Expr('RAND()'));
$_productCollection->load();
$_helper = $this->helper('catalog/output');
?>

<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
    <?php endif ?>
    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
            <?php
            $sb=0;
            $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
            if(count($imagesCount) >1 ):
                $_images = $imagesCount->getItemByColumnValue('label', 'back');
                if($_images)
                {
                    $sb=1;
                    ?>
                    <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize(203,270); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                <?php }
            endif;?>
            <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(203,270); ?>" width="203" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
        </a>
        <div class="datiProd">
             <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            <?php if($_product->getTypeId() != "bundle"): ?>
                <p class="sku"><?php echo $_product->getSku(); ?></p>
                <div class="doubleData">
                    <span class="tg">Tg. <?php echo $_product->getAttributeText("size"); ?></span>
                    <span class="lvl">Livello: <?php echo $_product->getAttributeText("livello"); ?></span>
                </div>
                <?php if($_product->getProdottoNuovo()): ?>
                    <span class="new">NUOVO</span>
                <?php endif; ?>
                <?php //if($_product->getPagamento() == 28): ?>
                    <!-- <span><?php echo $_product->getAttributeText("pagamento"); ?></span> -->
                <?php //endif; ?>
            <?php endif; ?>

            <?php if($_product->getPrezzoVisibile() == 1): ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
            <?php endif; ?>

            <div class="actions">
                <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                </ul>
                <?php if($_product->isSaleable()): ?>
                    <?php if($_product->getTypeId() != "downloadable"): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                        </button>
                    <?php else: ?>
                       <button type="button" title="<?php echo $this->__('Download') ?>" class="button btn-down" onclick="setLocation('<?php echo Mage::helper("checkout/cart")->getAddUrl($_product); ?>');">
                            <span><span><?php echo $this->__('Download') ?></span></span>
                        </button>
                    <?php endif; ?>
                <?php else: ?>
                    <!-- prodotto esaurito -->
                    <button type="button" title="<?php echo $this->__('Scopri') ?>" class="button btn-scopri-down" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                        <span><span><?php echo $this->__('Scopri') ?></span></span>
                    </button>
                <?php endif; ?>
            </div>
            <?php if($_product->getTypeId() == "configurable"): ?>
                <div class="addConf">
                    <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>" method="post" id="add-cart-form-<?php echo $_product->getId(); ?>">
                        <input type="hidden" name="related_product" value="" />
                        <input type="hidden" name="qty" value="1" />
                        <input type="hidden" name="cpid" value="" />
                        <input type="hidden" name="super_attribute[149]" value="" />
                    </form>
                    <?php
                    $conf = new Mage_Catalog_Block_Product_View_Type_Configurable();
                    $list = $conf->setData("product", $_product)->getAllowProducts();
                    foreach($list as $p): ?>
                        <button class="button select-product t-<?= $p->getTipologia(); ?>" data-sid="<?= $p->getId(); ?>" data-tipologia="<?= $p->getTipologia(); ?>" data-cid="<?= $_product->getId(); ?>">
                            <span><?= $p->getAttributeText('tipologia')." ". $this->helper("core")->formatPrice($p->getFinalPrice()); ?></span>
                        </button>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
    <?php endif ?>
<?php endforeach ?>

</div>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<script type="text/javascript">
    jQuery(document).on("click", "button.select-product", function(e)
    {
        e.preventDefault();
        $form = jQuery("#add-cart-form-" + jQuery(this).data("cid"));
        jQuery(" > input[name=product]", $form).val(jQuery(this).data("sid"));
        jQuery(" > input[name=cpid]", $form).val(jQuery(this).data("cid"));
        jQuery(" > input[name='super_attribute[149]']", $form).val(jQuery(this).data("tipologia"));
        $action = $form.attr("action");
        $action = $action.replace("/product/" + jQuery(this).data("cid"), "/product/" + jQuery(this).data("sid"));
        $form.attr("action", $action);
        $form.submit();
    });
</script>