<div class="home_blog">
    <h2 class="articles"><?= $this->__("ARTICLES") ?> <small><?= $this->__("Read our Blog"); ?></small></h2>
    <?php
        $collection = $this->getPosts()->clear();
        $collection
            ->setOrder('created_time', 'desc')
            ->excludeCatFilter(2)
            ->setPageSize(3)
            ->addFieldToFilter("vetrina", 1)
        ;
        $collection->getSelect()->group('post_id');
    ?>
    <?php 
        $i = 1;
        if (count($collection)): ?>
        <?php foreach ($collection as $post): ?>
                <?php $img= Mage::getBaseUrl('media').$post->getFotopost(); ?>
            <div class="postWrapper <?php if($i==3):?>last<?php endif; ?>">
                <div class="postImg">
                    <a href="/news/<?php echo $post->getIdentifier(); ?>/" >
                        <img src="<?php echo $img; ?>" width="205" height="273" />
                    </a>
                </div>
                <div class="postData">
                    <div class="postTitle">


                        <a href="/news/<?php echo $post->getIdentifier(); ?>/" ><?php echo $post->getTitle(); ?></a>
                    </div>
                    <div class="postDesc">
                        <p><?php echo substr(strip_tags($post->getShortContent()), 0, 80); ?>...</p>
                    </div>
                </div>
            </div>
            <?php $i++; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
    <?php endif; ?>
</div>

<div class="mobile-advertise-home">
   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('advertising-mobile-tablet')->toHtml(); ?>
</div>