<?php
$todayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$collection = Mage::getModel('catalog/product')->getCollection();
//$collection=$this->getLoadedProductCollection();
//Mage::getModel('catalog/layer')->prepareProductCollection($collection);
$collection->addAttributeToFilter('attribute_set_id','9');
$collection->addAttributeToSelect("*");
$collection->addAttributeToFilter("edicola",1);
$collection->addAttributeToFilter('news_from_date', array('date' => true, 'to' => $todayDate));
$collection->addAttributeToFilter('news_to_date', array('or'=> array(
        0 => array('date' => true, 'from' => $todayDate),
        1 => array('is' => new Zend_Db_Expr('null')))
    ), 'left');
$collection->setPageSize(2);
$collection->setOrder("id", "ASC");
$collection->addStoreFilter()
->addTierPriceData()
->addUrlRewrite()
->load()
;
$p = $collection->load()->getFirstItem();
echo ('---'. $todayDate);
?>

<?php foreach ($collection as $items): ?>
    <div class="product">
        <h4 class="product-name"><a href="<?php echo $items->getProductUrl(); ?>"><?php echo $items->getName(); ?></a></h4>
        <p class="sku"><?php echo $items->getSottoTitolo(); ?></p>
        <div class="leftProd">
            <a href="<?php echo $items->getProductUrl(); ?>"><img src="<?php echo $items->getImageUrl(); ?>" /></a>
        </div>
        <div class="rightProd">
		    <div><?php echo substr(strip_tags($items->getShortDescription()), 0, 60); ?>...</div>
            <button type="button" title="Scopri" class="button btn-scopri" onclick="setLocation('<?php echo $items->getProductUrl(); ?>')">
                <span><span>Scopri</span></span>
            </button>
        </div>
    </div>
<?php endforeach; ?>