<div class="megaforum">
    <h1><?php echo $this->__('Forum') ?></h1>
    <h2><?php echo $this->__('Modifica il post') ?></h2>
    <h3>Scambia idee e consigli con i membri della Community</h3>
    <?php
    $id = $this->getRequest()->getParam("id");
    $post = Mage::getModel('megaforum/post')->load($id);
    $topic = Mage::getModel('megaforum/topic')->load($post->getTopicId());
    ?>

    <form id="megaforum-form" enctype="multipart/form-data" method="post" action="<?php echo Mage::getUrl('megaforum/index/editme')?>">



        <div>
            <label for="title_field"><h2>Nome Argomento/Discussione</h2></label>
            <input id="topic_name" type="text" value="<?php echo $topic->getTopicName(); ?>" name="topic_name" readonly="readonly" />
            <input type="hidden" id="topic_id" type="text" value="<?php echo $topic->getTopicId(); ?>" name="topic_id" />
        </div>


        <div>
            <label for="content_field"><h2>Post<h2></label>
            <textarea id="post_text" class="required-entry" rows="10" cols="53" name="post_text"><?php echo $post->getPostText();?></textarea><br>
        </div>

        <input id="post_id" type="hidden" value="<?php echo $post->getpostId();?>" style="width: 450px;" name="post_id" />
        <input id="posted_at" type="hidden" value="<?php echo $post->getPostedAt();?>" style="width: 450px;" name="posted_at" />
        <input id="posted_by" type="hidden" value="<?php echo $post->getPostedBy();?>" style="width: 450px;" name="posted_by" />
        <input id="position" type="hidden" value="<?php echo $post->getPosition();?>" style="width: 450px;" name="position" />
        <input id="status" type="hidden" value="<?php echo $post->getStatus();?>" style="width: 450px;" name="status" />

        <button class="button btn-reply" type="submit" value="Salva Post">
            <span><span><?php echo $this->__('Salva Post') ?></span></span>
        </button>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('megaforum-form', true);
    //]]>
</script>


<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        relative_urls: false,
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
            username : "Some User",
            staffid : "991234"
        }
    });
</script>
