<div class="block block-blog block-forum">
    <div class="block-title">
        <h2 class="forum">Argomenti <small>del forum</small></h2>
    </div>
    <div class="block-content">
    <?php $forums = Mage::getModel('megaforum/forum')->getCollection(); ?>
        <div class="menu-categories">
            <ul>
        <?php foreach($forums as $forum): ?>
                <li><a href="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forum->getForumId()));  ?>">
                        <?php echo $forum->getForumName(); ?></a></li>
        <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
