<div class="page-title">
    <h1>Forum: messaggi privati</h1>
</div>
<div class="box-account box-recent">

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $privatemsgCollection = $this->getCollection(); ?>
    <?php echo $this->getPagerHtml(); ?>

    <table id="my-orders-table" class="data-table">
        <?php if (count($privatemsgCollection)){ ?>
        <thead>
        <tr class="first last">
            <th>Oggetto</th>
            <th>Inviato da</th>
            <th>Inviato il</th>
            <th>Dettagli</th>
            <th>Azione</th>
        </tr>
        </thead>
        <tbody>

        <!--<?php
        $customerData = Mage::getSingleton('customer/session')->getCustomer();
        $customerName = $customerData->getId();
        $privatemsgCollection = Mage::getModel('megaforum/privatemsg')->getCollection()->addFieldToFilter("sent_to", $customerName)->setOrder('privatemsg_id', 'DESC');
        ?>-->

        <?php
        foreach ($privatemsgCollection as $privatemsgCollections) {
            $customerData = Mage::getModel('customer/customer')->load($privatemsgCollections->getSentFrom());
            $firstname = $customerData->getFirstname();
            ?>

            <tr class="first last odd topics">
                <td><?php echo $privatemsgCollections->getSubject(); ?> </td>
                <td><?php echo $firstname; ?> </td>
                <td><?php echo $privatemsgCollections->getSentDate(); ?> </td>
                <td><?php echo $privatemsgCollections->getMessage(); ?> </td>
                <td><?php echo $this->formatDate($privatemsgCollections->getSentDate(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> </td>
                <td>
                    <a href="<?php echo Mage::getUrl('megaforum/index/reply') . "id/" . $privatemsgCollections->getPrivatemsgId() ?>">Rispondi</a> | <a
                        href="<?php echo Mage::getUrl('megaforum/index/privatemsgdelete') . "id/" . $privatemsgCollections->getPrivatemsgId() ?>">Elimina</a>
                </td>
            </tr>

        <?php } ?>
        <?php } else { ?>
            <tr class="vuoto" >
                <td colspan="4" >
                    <p style="margin: 0px 0 40px 0;">Nessun messaggio privato</p>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <script type="text/javascript">
        decorateTable('my-orders-table')
    </script>
</div>



