<div class="page-title">
    <h1>Forum: I miei Argomenti</h1>
</div>
<div class="box-account box-recent">
    <table id="my-orders-table" class="data-table">
        <thead>
        <?php
        if(count($topic)){ ?>
            <tr class="first last">
            <th style="width: 20%">Forum</th>
            <th style="width: 46%">Argomenti</th>
            <th style="width: 20%">Creato il</th>
            <th style="width: 14%">N° Post</th>
        </tr>
        </thead>
        <tbody>

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php $topic = $this->getCollection(); ?>
        <?php echo $this->getPagerHtml(); ?>


        <?php foreach ($topic as $topics) { ?>
            <?php /* Dan Nistor - view topics only for user created topics */ ?>
            <?php $customerSession = Mage::getSingleton('customer/session'); ?>
            <?php if ($customerSession->isLoggedIn()) : ?>
                <?php if ($topics->getCreatedBy() == $customerSession->getId()) : ?>
                    <?php
                    //Dan Nistor - no need to load customer
                    //$customerName = Mage::getModel('customer/customer')->load($topics->getCreatedBy());
                    $post = Mage::getModel('megaforum/post')->getCollection()->addFieldToFilter("topic_id", $topics->getTopicId());
                    $forum = Mage::getModel('megaforum/forum')->load($topics->getForumId());
                    ?>
                    <tr class="first last odd topics">
                        <td>
                            <a href="<?php echo Mage::getUrl('megaforum/index/index', array('forum_id' => $forum->getForumId()));  ?>">
                                <?php echo $forum->getForumName(); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo Mage::getUrl('megaforum/index/post')."id/".$topics->getTopicId() ?>" clas="name" >
                                <?php echo $topics->getTopicName(); ?>
                            </a>
                        </td>
                        <td><?php echo $this->formatDate($topics->getCreatedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?> </td>
                        <td><?php echo $post->count(); ?> </td>
                    </tr>
                <?php endif; ?>
            <?php endif; ?>
        <?php } ?>
        <?php } else { ?>
            <tr class="vuoto">
                <td colspan="4" >
                    <p style="margin: 0px 0 40px 0;">Nessun argomento inserito</p>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <script type="text/javascript">
        decorateTable('my-orders-table')
    </script>
</div>



