<h2><?php echo $this->__('Invia Messaggio Privato') ?></h2><br>

<div class="mega-forum megaforum">
<?php  
$id = $this->getRequest()->getParam("id");
$post = Mage::getModel('megaforum/post')->load($id); 
$customerName = Mage::getModel('customer/customer')->load($post->getPostedBy());
$forumUser = Mage::getModel('megaforum/forumuser')->getCollection()->addFieldToFilter("user_id",$customerName->getId())->getFirstItem(); 
?>

<form id="megaforum-form" enctype="multipart/form-data" method="post" action="<?php echo Mage::getUrl('megaforum/index/private', array('id' => $id))?>">

<div style="float:left;  margin-bottom:30px;">
    <?php if($customerName->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($customerName->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
    <img class="profile-image-private" src="<?= $img ?>" width="150" height="150" style="float:left; margin-bottom: 10px" >
    <br><label class="avtar-name"><?php echo $customerName->getSevenlikeNickname(); ?></label>
</div>

<div style="float:left; width:608px;" class="private-msg">
<div>
<label for="title_field"><h2><?php echo $this->__('Oggetto') ?><span class="required">*</span></h2></label>
<input id="subject" class="required-entry" type="text" value="" style="width: 630px;" name="subject"></input>
</div>

<div>
<label for="content_field"><h2><?php echo $this->__('Messaggio') ?><span class="required">*</span></h2></label>
<textarea id="message" class="required-entry" style="width: 450px;" rows="10" cols="53" name="message"></textarea><br><br>
</div>

<div class="button-set">

    <button class="topic-btn button btn-reply" type="submit"><span><span>Invia</span></span></button>
</div>

</div>
</form>
</div>

<script type="text/javascript">
   //<![CDATA[
    var dataForm = new VarienForm('megaforum-form', true);
   //]]> 
</script>

<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        relative_urls: false,
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
</script>


