<?php setlocale(LC_TIME, 'it_IT'); ?>

<?php $id = $this->getRequest()->getParam('id'); ?>
<?php if (is_null($id)) : ?>
    <?php $currentUser = Mage::getSingleton('customer/session'); ?>
    <?php if (!$currentUser->isLoggedIn()) : ?>
        <?php $redirectUrl = Mage::getUrl('community'); ?>
        <?php echo Mage::app()->getFrontController()->getResponse()->setRedirect($redirectUrl); ?>
    <?php else : ?>
        <?php $currentUser = $currentUser->getCustomer() ?>
    <?php endif; ?>
<?php else : ?>
    <?php $currentUser = Mage::getModel('customer/customer')->load($id); ?>
<?php endif; ?>

<div class="profile-root">
    <div class="profile-user">
        <div class="profile-image">
            <img src="<?php echo Mage::getUrl('media/customer') . $currentUser->getSevenlikeImage() ?>"/>
        </div>
        <div class="profile-nickname">
            <?php echo $currentUser->getSevenlikeNickname(); ?>
        </div>
        <div class="profile-description">
            <?php echo $currentUser->getSevenlikeDescription() ?>
        </div>
        <div class="profile-city">
            <?php echo $currentUser->getSevenlikeCity(); ?>
        </div>
        <div class="profile-nation">
            <?php echo $currentUser->getSevenlikeNation(); ?>
        </div>
        <div class="profile-name">
            <?php echo $currentUser->getFirstname() . ' ' . $currentUser->getLastname(); ?>
        </div>
        <div class="profile-active-from">
            <?php echo $this->__('Active from:') . ' ' . strftime('%e %B %Y', strtotime($currentUser->getCreatedAt())) ?>
        </div>
        <div class="profile-level">
            <?php echo $currentUser->getResource()
                ->getAttribute('sevenlike_level')
                ->getFrontend()
                ->getValue($currentUser)
            ?>
        </div>
    </div>
    <h2><?php echo $this->__('I miei post'); ?></h2>

    <div class="profile-user-post">

        <?php $userPostCollection = $this->getUserPostCollection(); ?>
        <?php echo $this->getPagerHtml(); ?>


        <?php foreach ($userPostCollection as $post) : ?>
            <?php $topic = Mage::getModel('megaforum/topic')->load($post->getTopicId()); ?>
            <?php $forum = Mage::getModel('megaforum/forum')->load($topic->getForumId()); ?>

            <div class="forum-name">
                <?php echo $forum->getForumName(); ?>
            </div>
            <div class="topic-name">
                <?php echo $topic->getTopicName() ?>
            </div>
            <div class="post-text">
                <?php echo $post->getPostText() ?>
            </div>
            <div class="post-time">
                <?php echo strftime('%e %B %Y', strtotime($post->getPostedAt())) ?>
            </div>
        <?php endforeach; ?>
    </div>
    <h2><?php echo $this->__('I miei topic'); ?></h2>

    <div class="profile-user-topic">

        <?php $userTopicCollection = Mage::getModel('megaforum/topic')
            ->getCollection()
            ->addFieldToFilter('created_by', $currentUser->getEntityId());
        ?>
        <?php foreach ($userTopicCollection as $topic) : ?>
            <?php $forum = Mage::getModel('megaforum/forum')->load($topic->getForumId()); ?>
            <div class="forum-name">
                <?php echo $forum->getForumName(); ?>
            </div>
            <div class="topic-name">
                <?php echo $topic->getTopicName() ?>
            </div>
            <div class="topic-time">
                <?php echo strftime('%e %B %Y', strtotime($topic->getCreatedAt())) ?>
            </div>
            <div class="topic-count">
                <?php $postCollection = Mage::getModel('megaforum/post')
                    ->getCollection()
                    ->addFieldToFilter('topic_id', $topic->getTopicId());
                ?>
                <?php echo $postCollection->getSize() ?>
            </div>
        <?php endforeach; ?>
    </div>
    <h2><?php echo $this->__('Le mie creazioni'); ?></h2>
    <ul class="products-grid">

        <?php $userCreationCollection = Mage::getModel('catalog/product')->getCollection()
            ->addAttributeToSelect(array('name', 'description', 'image', 'sku_cartamodello'))
            ->addAttributeToFilter('sku', array('like' => 'customer-creation-' . $currentUser->getId() . '%'))
            ->addAttributeToFilter('attribute_set_id', '10');
        ?>
        <?php $rowCount = 0; ?>
        <?php foreach ($userCreationCollection as $userProduct) : ?>

            <li class="item<?php echo $rowCount % 3 == 2 ? ' last' : null; ?>">

                <a href="<?php echo $userProduct->getProductUrl() ?>" class="product-image">
                    <img class="sbview" alt="<?php echo $userProduct->getName() ?>"
                         src="<?php echo $userProduct->getImageUrl() ?>" width="203" height="273"/>
                </a>


                <div class="datiProd">

                    <h2 class="product-name">
                        <a href="<?php echo $userProduct->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($userProduct->getName(), null, true) ?>">
                            <?php echo $userProduct->getName() ?>
                        </a>
                    </h2>

                    <div class="desc"><?php echo substr($userProduct->getDescription(), 0, 50); ?>...</div>

                    <button type="button" title="Scopri di pi&ugrave;" class="button btn-scopri"
                            onclick="setLocation('<?php echo $userProduct->getProductUrl() ?>')">
                        <span><span>Scopri</span></span>
                    </button>
                </div>
                <!--
                <div class="creation-info">
                    <?php /*echo $this->__('Carta Modello') */ ?>:
                    <?php /*echo $userProduct->getSkuCartamodello() */ ?>
                    <?php /*echo $this->__('Livello') */ ?>:
                </div>-->

            </li>
            <?php $rowCount++; ?>
        <?php endforeach; ?>
    </ul>

</div>

