<?php setlocale(LC_TIME, 'it_IT'); ?>

<?php $id = $this->getRequest()->getParam('id'); ?>
<?php if (is_null($id)) : ?>
    <?php $currentUser = Mage::getSingleton('customer/session'); ?>
    <?php if (!$currentUser->isLoggedIn()) : ?>
        <?php $redirectUrl = Mage::getUrl('community'); ?>
        <?php echo Mage::app()->getFrontController()->getResponse()->setRedirect($redirectUrl); ?>
    <?php else : ?>
        <?php $currentUser = $currentUser->getCustomer() ?>
    <?php endif; ?>
<?php else : ?>
    <?php $currentUser = Mage::getModel('customer/customer')->load($id); ?>
<?php endif; ?>

<div class="profile-root">
    <div class="profile-user">
        <div class="left-profile">
            <?php if($currentUser->getSevenlikeImage()) $img = $this->getUrl('media/customer') . substr($currentUser->getSevenlikeImage(), 1); else $img = $this->getSkinUrl('images/blog/avatar.png'); ?>
            <img src="<?= $img ?>" width="150" height="150">
        </div>
        <div class="right-profile">
            <h2><?php echo $currentUser->getSevenlikeNickname(); ?></h2>
            <div class="profile-description">
                <?php echo $currentUser->getSevenlikeDescription() ?>
            </div>
            <div class="profile-active-from">
                <?php echo $this->__('Attivo dal:') . ' ' . strftime('%e %B %Y', strtotime($currentUser->getCreatedAt())) ?>
            </div>
            <div class="profile-city">Citt&agrave;: <span><?php echo $currentUser->getSevenlikeCity(); ?></span></div>
            <div class="profile-nation">Nazione: <span><?php echo $currentUser->getSevenlikeNation(); ?></span></div>

            <div class="profile-level">Conoscenze di cucito:
                <span>
                    <?php echo $currentUser->getResource()
                        ->getAttribute('sevenlike_level')
                        ->getFrontend()
                        ->getValue($currentUser)
                    ?>
                </span>
            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('megaforum.profile.post'); ?>
    <?php echo $this->getChildHtml('megaforum.profile.topic'); ?>
    <?php echo $this->getChildHtml('megaforum.profile.creation'); ?>

</div>
