<html>
<head>
    <title>Prova Titolo</title>   
    <meta charset="UTF-8">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script> 
    <script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/uploadify/jquery.uploadify.js"></script>
    <link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/js/uploadify/uploadify.css">
    
    <link href="/js/videojs/video-js.css" rel="stylesheet">
	<script type="text/javascript" src="/js/videojs/video.js"></script>
	<script type="text/javascript" src="/js/purple.js"></script>
	<script type="text/javascript">document.domain = "burdastyle.it"</script>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>