<div style="width: 80%; align: center;" id="boxButton">
	<table align=center width="60%">
		<tr>
			<td align="left">
				<form method="post" enctype="multipart/form-data">
					<input type="file" name="uploadedfile" id="uploadedfile" value="Upload Video" />
				</form>
			</td>
			<td align="left">
				o seleziona un video caricato via ftp
				<select onchange="return useFTPfile()" id="use_ftp_file">
					<option value=""></option>
					<?php
						$uploaded_files = scandir("/var/www/burdastyle.it/media/blfa_files", SCANDIR_SORT_ASCENDING);
						array_shift($uploaded_files);
						array_shift($uploaded_files);
						foreach ($uploaded_files as $file) {
							echo "<option value='" . rawurldecode($file) . "'>" . htmlspecialchars($file) . "</option>";
						}
					?>
				</select>
			</td>
			<?php if ($this->video->getVideoId() !== null) : ?>
				<td>
					<form method="post" action="/video/delete">
						<input type="submit" name="delvideo" id="delvideo" value="Cancella Video" />
						<input type="hidden" name="video_id" id="video_id" value="<?php echo $this->video->video_id; ?>" />
						<input type="hidden" name="product_id" id="product_id" value="<?php echo $this->product_id; ?>" />
						<input type="hidden" name="auth_token"  value="<?php echo $this->auth_token; ?>" />
					</form>			
				</td>
			
				<td>
					<form method="post" enctype="multipart/form-data">
						<input type="file" name="uploadedSlide" id="uploadedSlide" value="Upload Slide" />					
					</form>		
				</td>
				<td>
					<form method="post" action="/slides/delete">
						<input type="submit" name="delslide" id="delslide" value="Cancella Slide" />
						<input type="hidden" name="video_id" id="video_id" value="<?php echo $this->video->video_id; ?>" />
						<input type="hidden" name="auth_token"  value="<?php echo $this->auth_token; ?>" />						
					</form>
				</td>
			<?php endif; ?>
		</tr>
	</table>
<?php $timestamp = time(); ?>

<div id="video_container" align="center">
	<video id="videojs_editor_id" class="video-js vjs-default-skin"
	  controls preload="auto" width="640" height="264"
	  data-setup='{"example_option":true}'>
	  <?php if ($this->video->getVideoId() != null) : ?>
		<source src="<?php echo $this->video->getVideoPath() . "?mktime=" . $timestamp; ?>" type='video/mp4' />
	  <?php endif; ?>
	 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
	</video>
</div>


<br /><br />

<div id="boxSlide" style="width: 80%; align: center; margin: auto">
	<table>
		<tr>
			<?php foreach ($this->slides as $slide): ?>	
			    <td>			     
			    	<a onclick="addTime('<?php echo $slide->slide_id; ?>', '<?php echo $this->video->video_id; ?>', '<?php echo $this->auth_token; ?>')" href="javascript: void(0)">[add]</a>
			    	<img src="<?php echo $slide->slide_path; ?>" border=0 height=50 />	    	
			    </td>
			<?php endforeach ?>
	    </tr>
	</table>
	
		
	<hr>
	
<?php /*?>	
	<table>
		<tr id="TRslidetime">
			<?php foreach ($this->slides as $slide): 
					$slide_id = $slide->getSlideId();
					if (isset($this->arrSlidesTimes[$slide_id]) && $this->arrSlidesTimes[$slide_id] != null) {	
						$slideTime = $this->arrSlidesTimes[$slide_id][0];
				?>	
					    <td id="stbox_<?=$slide_id; ?>" style="min-width: 70px; border:1px solid #FF000=; min-height: 50px">
					    	<a href="javascript: void(0)" id="<?=$slideTime->slide_time_id; ?>" onclick="deleteTime('<?=$slideTime->slide_time_id; ?>','<?php echo $slide_id; ?>', 'true')">[x]</a>
					    	<span><?=$slideTime->slide_opening_time; ?></span>	    	
					    </td>
			<?php } endforeach ?>    	    
	    </tr>
	</table>
<?php */ ?>
</div>

<br /><br />

<div id="slidewithtimebox" style="width: 80%; align: center; margin: auto">	
</div>


</div>

<script type="text/javascript">
	$(function() {
		$('#uploadedfile').uploadify({
			'formData'     : {	
				'product_id' : '<?php echo $this->product_id; ?>',			
				'video_id' : '<?php echo $this->video->video_id; ?>',
				'auth_token' : '<?php echo $this->auth_token; ?>',
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
			},
			'buttonText' : 'Carica il video',
			'fileObjName' : 'uploadedfile',
			'fileTypeDesc' : 'Carica il video',
			'fileTypeExts' : '*.mp4',
			'swf'      : '<?php echo '/js/uploadify/uploadify.swf'; ?>',
			'uploader' : '<?php echo $this->baseUrl('/video/upload'); ?>',
			'onUploadSuccess' : function(file, data, response) {
				alert(data);
				location.reload();		        
		    }
		});
	});
		
	$(function() {
		$('#uploadedSlide').uploadify({
			'formData'     : {	
				'product_id' : '<?php echo $this->product_id; ?>',			
				'video_id' : '<?php echo $this->video->video_id; ?>',
				'auth_token' : '<?php echo $this->auth_token; ?>',
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
			},
			'buttonText' : 'Carica le slide',
			'fileObjName' : 'uploadedSlide',
			'fileTypeDesc' : 'Carica le slide',
			'fileTypeExts' : '*.zip',
			'swf'      : '<?php echo '/js/uploadify/uploadify.swf'; ?>',
			'uploader' : '<?php echo $this->baseUrl('/slides/upload'); ?>',
			'onUploadSuccess' : function(file, data, response) {
				alert(data);
				location.reload();
		    }
		});
	});


	$(document).ready(function(){	
		populateBoxSlidesWithTimes('<?php echo $this->video->video_id; ?>', '<?php echo $this->auth_token; ?>')			
	});

	function useFTPfile() {
		var url = '<?php echo $this->baseUrl('/video/useexisting'); ?>'
		var selected_file = $("#use_ftp_file").val();
		if (selected_file.length == 0) return;

		window.location = url + "?product_id=<?= $_REQUEST["product_id"] ?>&auth_token=<?= $_REQUEST["auth_token"] ?>&file=" + selected_file;

		return false;
	}
</script>
