<table width="70%" align="center" border=1>
<tr>
	<td colspan=4 align="center">TABELLA VIDEO</td>
</tr> 
<tr>    
    <td>id</td>
    <td>prodottoid</td>
    <td>videopath</td>
    <td>videosize</td>    
</tr>
<tr>
    <?php foreach ($this->entries as $entry): ?>
    <td><?php echo $this->escape($entry->video_id) ?></td>
    <td><a href="/video/video?productId=<?=$entry->product_id; ?>"><?php echo $this->escape($entry->product_id) ?></a></td>
    <td><?php echo $this->escape($entry->video_path) ?></td>
    <td><?php echo $this->escape($entry->video_size) ?></td>
    <?php endforeach ?>
</tr>
</table>