<!-- <h1>VIDEO</h1> -->


<div id="video_container">
	<video id="videojs_id" class="video-js vjs-default-skin"
	  controls preload="auto" width="100%" height="100%"
	  data-setup='{"example_option":true}'>
	 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
	</video>
</div>

<input id="product_id" type="hidden" name="product_id" value="<?php echo $this->product_id; ?>" />

<div id="slides_container" style="display: none;">
	<img id="slide_selected" alt="slide attiva" src="" />
	<input type="hidden" id="slide_time_id" name="slide_time_id" value="" />
	<ul id="slides_times_container">
		
	</ul>
</div>