<div>
<h1>UPLOAD VIDEO</h1>
<form enctype="multipart/form-data" action="/video/upload" method="POST">
    <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
    <input type="hidden" name="productId" value="100" />
    <input type="hidden" name="videoId" value="1" />
       VIDEO <input name="uploadedfile" id="videoUpload" type="file" />
    <br /><br /><br />
    <input type="submit" value="Upload File" />
</form>
</div>