<div>

<form>
<table width="60%" align="center">
	<tr>
		<td><input type="button" value="update video"></td>
		<td><input type="button" value="update slide"></td>
		<td><input type="button" value="delete slide"></td>
	</tr>
</table>
</form>


<div style="width: 700px; height:500px; border: 1px solid #FF0000; margin: auto;">
	
</div>

<table width="60%" align="center">
	<tr>
		<td>img</td>
		<td>img</td>
		<td>img</td>
		<td>img</td>
		<td>img</td>
	</tr>
	<tr>
		<td>img</td>
		<td>img</td>
		<td>img</td>
		<td>img</td>
		<td>img</td>
	</tr>
</table>

</div>