<div>
<?php
//echo "SSSSSSSSSSSSSS : ".$this->baseUrl();
//$this->form->setAction($this->url());
//echo $this->form;
?>

<div>
<h1>UPLOAD VIDEO</h1>
<form enctype="multipart/form-data" action="/video/upload" method="POST">
    <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
    <input type="hidden" name="productId" value="100" />
    <input type="hidden" name="videoId" value="" />
       VIDEO <input name="uploadedfile" id="videoUpload" type="file" />
    <br /><br /><br />
    <input type="submit" value="Upload File" />
</form>
</div>

<hr>

<div>
<h1>UPLOAD SLIDES</h1>
<form enctype="multipart/form-data" action="/slides/upload" method="POST">
    <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
    <input type="hidden" name="productId" value="100" />
    <input type="hidden" name="videoId" value="1" />
       ZIP <input name="uploadedzip" id="zipUpload" type="file" />
    <br /><br /><br />
    <input type="submit" value="Upload File" />
</form>
</div>

<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#videoUpload').uploadify({
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
			},
			'swf'      : '<?php echo $this->baseUrl('/js/uploadify/uploadify.swf'); ?>',
			'uploader' : '/video/upload'
		});
	});
</script>
	

</div>