<div>
<?php
//$this->headScript()->appendFile('/js/jquery.uploadify.js');
//$this->headScript()->appendFile('/js/jquery.uploadify.min.js');
//$this->headLink()->appendStylesheet($this->baseUrl('/css/uploadify.css'));

echo "SSSSSSSSSSSSSS : ".$this->baseUrl();
$this->form->setAction($this->url());
echo $this->form;
?>

<script type="text/javascript">
		<?php $timestamp = time();?>
		$(function() {
			$('#slidesVideo').uploadify({
				'formData'     : {
					'timestamp' : '<?php echo $timestamp;?>',
					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
				},
				'swf'      : '<?php echo $this->baseUrl('/css/uploadify.swf');?>',
				'uploader' : 'uploadify.php'
			});
		});
	</script>

</div>