<div class="mobileNavigation">


<div class="topMobileNav">
	<div class="backToDesk"></div>
	<div class="titleTopMobileNav">MENU</div>
	<div class="activeTopMobileNav"></div>
</div>



	<?php $_helper       = Mage::helper('catalog/category') ?>
	<?php $_categories   = $_helper->getStoreCategories() ?>
	<?php $i = 1; ?>

    <?php if (count($_categories) > 0): ?>
    <ul id="nav">
        <?php foreach($_categories as $_category): ?>

            <!-- DEFINISCO SOTTOCAEGORIE E CLASSI -->
            <?php $figli = Mage::getModel('catalog/category')->getCategories($_category->getId()); ?>
            <?php $quanti = $figli->count(); ?>
            <?php if(isset($current) and $current==$_category->getId()) $active = 'active'; else $active = ''; ?>
            <?php if(isset($neha) and $neha) $parent = 'parent'; else $parent = ''; ?>
            <!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->


            <li class="level0 nav-<?= $i; ?> level-top <?= $active.' '.$parent; ?>">
                <a href="<?= $_helper->getCategoryUrl($_category) ?>" class="level-top <?php if($quanti > 0): ?>parent<?php endif; ?>" data-sub="<?= $_category->getId(); ?>">
                    <?= $_category->getName(); ?>
                </a>

                <?php if($quanti > 0):?>
                	<ul class="level0">
	                     <?php foreach ($figli as $categore): ?>
                            <li class="level1 nav-<?= $i."-".@$a; ?>">
                              <a href="<?= $_helper->getCategoryUrl($categore) ?>">
                              <?= $categore->getName(); ?>
                              </a>
                            </li>
	                     <?php endforeach; ?>
                	</ul>
                <?php endif; ?>
            </li>

            <?php $i++; ?>
        <?php endforeach; ?>

    </ul>
    <?php endif; ?>

</div>