<?php
$cp = Mage::getModel("product/product")
    ->getCollection()
    ->setOrder("id", "DESC")
    ->setPageSize(2);
?>
<hr class="separator-x">
<div class="block block-mostRead">
    <h2 class="mostRead">Le Ultime <small>creazioni</small></h2>
    <ul>
        <?php foreach($cp as $creazione): ?>
            <?php
            $customer = Mage::getModel("customer/customer")->load($creazione->getIdCustomer());

            $creazioneProd = Mage::getModel("catalog/product")
                ->getCollection()
                ->addFieldToFilter("entity_id", $creazione->getIdProduct())
//            ->addAttributeToSelect(array("name", "sku_cartamodello", "image"))
                ->addAttributeToSelect("*")
                ->addUrlRewrite()
                ->getFirstItem()
            ;

            $cartamodello = Mage::getModel("catalog/product")
                ->getCollection()
                ->addFieldToFilter("sku", $creazioneProd->getSkuCartamodello())
                ->addAttributeToSelect(array("name", "livello"))
                ->addUrlRewrite()
                ->getFirstItem()
            ;
            ?>
            <li>
                <div class="img">
                    <a href="<?php echo $creazioneProd->getProductUrl(); ?>" class="title">
                        <img src="<?php echo $this->helper('catalog/image')->init($creazioneProd, 'thumbnail')->resize(203,270); ?>" width="112">
                    </a>
                </div>

                <div class="det">
                    <a href="<?php echo $creazioneProd->getProductUrl(); ?>" class="title"><?php echo $creazioneProd->getName(); ?></a>
                    <p class="dati">
                        <?php echo $this->formatDate($creazioneProd->getCreatedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?>
                        <br><?php echo $this->__("by"); ?> <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customer->getId() ?>"><span class="writer"><?php echo $customer->getSevenlikeNickname(); ?></a></span>
                    </p>

                    <?php if($cartamodello->getId()): ?>
                        <p class="etichetta">Cartamodello: <a href="<?php echo $cartamodello->getProductUrl(false); ?>"><span><?php echo $creazioneProd->getSkuCartamodello(); ?></span></a></p>
                    <?php elseif($creazioneProd->getSkuCartamodello()): ?>
                        <p class="etichetta">Cartamodello: <span><?php echo $creazioneProd->getSkuCartamodello(); ?></span></p>
                    <?php endif; ?>

                    <?php if($cartamodello->getId()): ?>
                        <p class="etichetta lvl">Livello: <span><?php echo $cartamodello->getAttributeText('livello'); ?></span></p>
                    <?php endif; ?>

                    <p><?php echo substr($creazioneProd->getDescription(), 0, 60); ?>...</p>

                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>