<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<?php
    /**
    * Product list template
    *
    * @see Mage_Catalog_Block_Product_List
    */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products creazioni-utente">
        <?php echo $this->getToolbarHtml() ?>
        

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php
                $cp = Mage::getModel("product/product")
                    ->getCollection()
                    ->addFieldToFilter("id_product", $_product->getId())
                    ->getFirstItem();
                $customer = Mage::getModel("customer/customer")->load($cp->getIdCustomer());

                $cartamodello = Mage::getModel("catalog/product")
                    ->getCollection()
                    ->addFieldToFilter("sku", $_product->getSkuCartamodello())
                    ->addAttributeToSelect("livello")
                    ->addUrlRewrite()
                    ->getFirstItem()
                ;
            ?>
            <?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
                    <?php endif;  ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php
                        $sb=0;
                        $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                        if(count($imagesCount) >1 ):
                            $_images = $imagesCount->getItemByColumnValue('label', 'back');
                            if($_images)
                            {
                                $sb=1;
                            ?>
                            <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize(400,537); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                            <?php }
                            endif;?>
                    <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400,537); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="datiProd">
                    <div class="doubleData">
                        <span>
                            <?php echo $this->formatDate($_product->getCreatedAt(), Mage::getStoreConfig('blog/blog/dateformat'), false); ?>
                        <br>
                            <a href="<?php echo Mage::getUrl('megaforum/index/profile')."id/".$customer->getId() ?>"><?php echo $customer->getSevenlikeNickname(); ?></a>
                        </>
                    </div>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php /*if($cartamodello->getId()): */?><!--
                        <p class="sku">Cartamodello: <a href="<?php /*echo $cartamodello->getProductUrl(false); */?>"><?php /*echo $_product->getSkuCartamodello(); */?></a></p>
                    <?php /*elseif($_product->getSkuCartamodello()): */?>
                        <p class="sku">Cartamodello: <?php /*echo $_product->getSkuCartamodello(); */?> </p>
                    --><?php //endif; ?>


                   <!-- <?php /*if($cartamodello->getId()): */?>
                        <p class="sku">Livello: <?php /*echo $cartamodello->getAttributeText('livello'); */?></p>
                    <?php /*endif; */?>-->

                    <div class="desc"><?php echo substr($_product->getDescription(), 0, 50); ?>...</div>

                    <button type="button" title="Scopri di pi&ugrave;" class="button btn-scopri" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                        <span><span>Scopri</span></span>
                    </button>
                </div>

            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>
    <script type="text/javascript">
        decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);
    </script>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>