<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<?php
    /**
    * Product list template
    *
    * @see Mage_Catalog_Block_Product_List
    */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	$_mediaserver_helper = $this->helper('mediaserver');
	$db = Mage::getSingleton('core/resource')->getConnection('core_read');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products category-video">
        <?php echo $this->getToolbarHtml() ?>
        <?php $_collectionSize = $_productCollection->count() ?>
		<ul class="products-list">
        <?php foreach ($_productCollection as $_product): ?>
			<?php $video = $db->fetchRow("SELECT * FROM sl_mediaserver_videos WHERE product_id=?", $_product->getid()) ?>
            <li>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-video">
                    <?php
                        $sb=0;
                        $imagesCount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                        if(count($imagesCount) >1 ):
                            $_images = $imagesCount->getItemByColumnValue('label', 'back');
                            if($_images) {  $sb=1;
                            ?>
                            <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_images->getFile())->resize(326,196); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                            <?php }
                            endif;?>
                            <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(326,196); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <?php if($_product->getPagamento() == 28): ?>
                               <span class="new free"><?php echo $_product->getAttributeText("pagamento"); ?></span>
                            <?php else: ?>
                                <span class="preview">Free Preview</span>
                            <?php endif; ?>
                </a>
                <div class="datiProd">
                    <h2 class="video-name">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </h2>
                    <!-- <h4 class="pubblicazione">Pubblicato: <span>16/04/1987</span></h4> -->
                    <div class="video-desc">
                        <?php echo $_product->getShortDescription(); ?>
                    </div>
                    <div class="more-dati">
					    <!-- <p class="video-durata">DURATA: <span><?= gmdate("H:i:s", $video["video_length"]) ?></span></p> -->
                        <!-- <p class="video-categoria">CATEGORIA: <span>Pubblicità</span></p> -->
                        <p class="video-wish"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Aggiungi ai preferiti') ?></a></p>
                    </div>
                    <div class="actions">
                        <?php if ($_mediaserver_helper->isVideoBought($_product->getId()) || $_product->getPagamento() == 28): ?>
							<a href="<?php echo $_product->getProductUrl() ?>?play=1"><?= $this->__("Visualizza il video") ?></a>
						<?php elseif($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                <span><span><?php echo $this->__('Acquista<br />singolo video') ?></span><?php echo $this->getPriceHtml($_product, true) ?></span>
                            </button>
                        <?php else: ?>
                            <!-- prodotto esaurito -->
                            <button type="button" title="<?php echo $this->__('Scopri') ?>" class="button btn-scopri-down" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                <span><span><?php echo $this->__('Scopri') ?></span></span>
                            </button>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
		<script type="text/javascript">
			decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);
		</script>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>