<?php

/**
* Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>

<?php   
$_LINK = "";
 $config = Mage::getStoreConfig('moreview_section/general_group/module_moreview');
    if($config == 1):
    ?>
    <?php if(count($this->getItemCollection()->getItems())): ?>
        <div class="box-collateral box-up-sell">
            <ol class="mini-products-list products-grid" id="block-upsell">
                <?php $this->resetItemsIterator() ?>
                <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                            <li class="item <?php if($_j==2):?>last<?php endif; ?>">
                                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                                    <?php
                                        $sb=0;
                                        $imagesCount = Mage::getModel('catalog/product')->load($_link->getId())->getMediaGalleryImages();
                                        if(count($imagesCount) >1 ):
                                            $_images = $imagesCount->getItemByColumnValue('label', 'back');
                                            if($_images)
                                            {
                                                $sb=1;
                                            ?>
                                            <img class="sbmoreview" src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail', $_images->getFile())->resize(400,537); ?>" alt="<?php echo $this->htmlEscape($_images->getLabel());?>" title="<?php $this->htmlEscape($_images->getLabel());?>"/>
                                            <?php }
                                            endif;?>

                                    <img class="<?php if($sb==1)echo "sbview";?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(400,537) ?>"  alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                                <div class="datiProd">
                                    <h2 class="product-name">
                                        <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a>
                                    </h2>
                                    <?php if($_link->getTypeId() != "bundle"): ?>
                                        <p class="sku"><?php echo $_link->getSku(); ?></p>
                                        <div class="doubleData">
                                            <span class="tg">Tg. <?php echo $_link->getAttributeText("size"); ?></span>
                                            <span class="lvl">Livello: <?php echo $_link->getAttributeText("livello"); ?></span>
                                        </div>
                                        <?php if($_link->getProdottoNuovo()): ?>
                                            <span class="new">NUOVO</span>
                                        <?php endif; ?>

                                    <?php else: ?>
                                        <p class="sku"><?php echo $_link->getShortDescription(); ?></p>
                                        <div class="doubleData">
                                            <span class="lvl">Livello: <?php echo $_link->getAttributeText("livello"); ?></span>
                                        </div>
                                    <?php endif; ?>

                                    <?php if($_link->getPrezzoVisibile() == 1): ?>
                                        <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                                    <?php endif; ?>

                                    <div class="actions">
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?= $this->getAddToWishlistUrl($_LINK) ?>" class="link-wishlist">
                                                    <?php echo $this->__('Add to Wishlist') ?>
                                                </a></li>
                                            <?php endif; ?>
                                        </ul>
                                        <?php if($_link->isSaleable()): ?>
                                             <?php if($_link->getTypeId() != "downloadable"): ?>
                                                <button type="button" title="<?= $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?= $this->getAddToCartUrl($_link) ?>')">
                                                    <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                                </button>
                                            <?php else: ?>

                                               <button type="button" title="<?= $this->__('Download') ?>" class="button btn-down" onclick="setLocation('<?= Mage::helper("checkout/cart")->getAddUrl($_link); ?>');">
                                                    <span><span><?php echo $this->__('Download') ?></span></span>
                                                </button>


                                            <?php endif; ?>
                                        <?php else: ?>
                                            <!-- prodotto esaurito -->
                                            <button type="button" title="<?php echo $this->__('Scopri') ?>" class="button btn-scopri-down" onclick="setLocation('<?php echo $_link->getProductUrl() ?>')">
                                                <span><span><?php echo $this->__('Scopri') ?></span></span>
                                            </button>
                                        <?php endif; ?>
                                    </div>

                                    
                                    <?php if($_link->getTypeId() == "configurable"): ?>
                                        <div class="addConf">
                                            <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($_link); ?>" method="post" id="add-cart-form-<?php echo $_link->getId(); ?>">
                                                <input type="hidden" name="related_product" value="" />
                                                <input type="hidden" name="qty" value="1" />
                                                <input type="hidden" name="cpid" value="" />
                                                <input type="hidden" name="super_attribute[149]" value="" />
                                                <?php
                                                $conf = new Mage_Catalog_Block_Product_View_Type_Configurable();
                                                $list = $conf->setData("product", $_link)->getAllowProducts();
                                                foreach($list as $p): ?>
                                                    <button class="button select-product t-<?= $p->getTipologia(); ?>" data-sid="<?= $p->getId(); ?>" data-tipologia="<?= $p->getTipologia(); ?>" data-cid="<?= $_link->getId(); ?>">
                                                        <span><?= $p->getAttributeText('tipologia')." ". $this->helper("core")->formatPrice($p->getFinalPrice()); ?></span>
                                                    </button>
                                                <?php endforeach; ?>
                                            </form>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    <?php endfor; ?>
            </ol>
            <script type="text/javascript">decorateTable('upsell-product-table')</script>
        </div>
        <?php endif ?>
    <?php endif ?>
