<div id="opc-discount-block">
    <form id="opc-discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
        <div class="discount">
            <div class="discount-form">
                <!--<label for="coupon_code">Hai un codice sconto?</label>-->
                <div class="input-box">
                    <input class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" autocomplete="off"/>
                    <?php if(strlen($this->getCouponCode())): ?>
                         <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button remove-coupon right"  value="<?php echo $this->__('Cancel') ?>">
                            <span><span><?php echo $this->__('Cancel') ?></span></span>
                        </button>
                     <?php else:?>
                        <button type="button" title="<?php echo $this->__('Apply') ?>" class="button apply-coupon"  value="<?php echo $this->__('Applica') ?>">
                            <span><span><?php echo $this->__('Applica') ?></span></span>
                        </button>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var CouponForm = new VarienForm('opc-discount-coupon-form', true);
    $('coupon_code').observe('keypress', bindCouponPost);
    function bindCouponPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            evt.preventDefault();
            $j(".apply-coupon").click();
        }
    }
    //]]>
</script>
